### ISSUE TITLE
Cataclysm Support?

### ISSUE THREAD

**Issue by xiibo** [Skamer/Syling-Tracker#100]
Is there any plan on updating this for Cataclysm? I was just wondering, since it seems like it was supported during WOTLK.

**Comment by Skamer** [comment]
Hello,

It's in my plan with Vanilla classic as well. 
I had made a support of WoTLK, but the problem was this version was too far behind the retail one. I'm reviewing my way of doing things in order to avoid that in the future.

**Comment by Skamer** [comment]
Little update. 

I'm going to start supporting Cataclysm and Vanilla as well. I don't an ETA to give but i'd like to finish this before the release of The War Within.

**Comment by xiibo** [comment]
Glad to hear it, looking forward to using it

**Comment by Skamer** [comment]
I have an early build available in a separate branch "feature/classic-support", you can download it from the "Action" tab, then choose a commit with "feature/classic-support".

![image](https://github.com/user-attachments/assets/8cc73c3e-e74e-46fe-b5e7-d62ba13d59ce)

Then at the bottom, you should see the addon package that you can download (you need to be logged into Github).
![image](https://github.com/user-attachments/assets/2a4453a3-4876-46d0-b9ea-ebad1f51ca12)

Each commit that i publish on this branch will create automatically a packaged version of the addon. You can repeat these steps to update the addon. I know it's not ideal, but the classic support has required a reorganization of all the files and folders which affect also the retail version. With the extension coming soon, i didn't want to risk breaking something and ruining the player experience. But in the future and with more tests, i will merge the branch into the main one.

This is an early support, and a lot of things still need to be fixed and updated.

**Comment by Skamer** [comment]
I merged the classic support in the main branch, so from 2.5.0 version the addon now support all game versions in a same package. Take note lot of thing remain to be done but the base features should be here and working.
