### ISSUE TITLE
Function 'QuestSuperTracking_OnQuestTracked' removed, causing LUA errors when accepting new quests

### ISSUE THREAD

**Issue by Asterism314** [Skamer/Syling-Tracker#104]
**Describe the bug**
Getting an LUA error when accepting new quests.

**Do you have an error log of what happened?**

Message: ...face/AddOns/SylingTracker/Contents/Quests/Quests.lua:437: attempt to call global 'QuestSuperTracking_OnQuestTracked' (a nil value)
Time: Wed Aug 21 21:08:52 2024
Count: 1
Stack: ...face/AddOns/SylingTracker/Contents/Quests/Quests.lua:437: attempt to call global 'QuestSuperTracking_OnQuestTracked' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Scorpio/Modules/Core.lua"]:78: in function <Interface/AddOns/Scorpio/Modules/Core.lua:73>
[string "=(tail call)"]: ?

**To Reproduce**
1. Accept a quest.

**What is the version of SylingTracker you use ?**
2.4.2

**What are the versions of PLoop and Scorpio you use ?**
- PLoop: Not installed.
- Scorpio: 'r219'

**Comment by Skamer** [comment]
Fixed in the 2.4.3 

Strangely i don't encounter this error when accepting the quest, this is why i don't noticed the function has been removed by blizzard.  Thanks for reporting it.

**Comment by Asterism314** [comment]
Confirmed resolved with the latest update.
