### ISSUE TITLE
"Show Details" window

### ISSUE THREAD

**Issue by Arkewas** [Skamer/Syling-Tracker#107]
Hello,
when I right-click on  a quest and select "Show details" the result is a empty window with the word "Description" only. Also when this issue is fixed would it to be  possible to make the "Show details"  option as the default one when I left click on a quest ?. In my opinion this  windows is more compact and readable than the default "World map with objective description" and furthermore it already has a "Show map" button.
Thanks in advance
![Syling tracker empty description](https://github.com/user-attachments/assets/8ee5d43e-12cc-4269-8dea-c353627cd10c)
![World map with objective description](https://github.com/user-attachments/assets/39c5ddf3-0b4d-4646-8426-4616bbe72bcb)

**Comment by Skamer** [comment]
Hello,

The fix will be included in the 2.5.0.

> Also when this issue is fixed would it to be possible to make the "Show details" option as the default one when I left click on a quest ?

A way will be added in the future for changing the behavior of left, middle and right click.

**Comment by Arkewas** [comment]
Good news, thank you very much.
