### ISSUE TITLE
[Cataclysm Classic] autocomplete quest popup not working

### ISSUE THREAD

**Issue by Road-block** [Skamer/Syling-Tracker#110]
**Describe the bug**
Some quests get an autocomplete popup on the tracker (Blizz) where you can complete them "on the go".

**Do you have an error log of what happened?**
If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 
There are no Lua errors, this must be an implementation/logical bug.

**To Reproduce**
Example quest.
1. Got [Guardians of Hyjal: Call of the Ancients](https://www.wowhead.com/cata/quest=29391)
2. Completed quest.
3. With Syling Tracker enabled I have no way to turn in (no popup and click not working)
4. Disabling the addon I get the popup on the default Blizzard tracker.

**Expected behavior**
It would be nice to quest seamlessly without having to disable/reload to turn in autocomplete quests 

**Screenshots**
Default Tracker
![image](https://github.com/user-attachments/assets/1a6f0a59-8699-441d-90e0-08962d7ef37b)
Syling Tracker
![image](https://github.com/user-attachments/assets/d4e79e65-283c-4830-a860-9e2522bd1e6c)

**What is the version of SylingTracker you use ?**
v2.5.2

**What are the versions of PLoop and Scorpio you use ?**
- PLoop: 'Put the version here'
- Scorpio: r221

**Additional context**

**Comment by Road-block** [comment]
There is a slightly better workaround than disabling the addon.

Can temporarily toggle the "show blizzard objective tracker" from the options, but that is not ideal as well 🙂

**Comment by Road-block** [comment]
Following changes will stop errors and let us at least click to complete as intended. (_I'd still prefer some kind of popup to make it obvious_)

[/Cataclysm/Contents/Quests/Quests.lua#L31](https://github.com/Skamer/Syling-Tracker/blob/de60823b850d9cf93e0e9c29027bd279df9a6ae0/Cataclysm/Contents/Quests/Quests.lua#L31)
add
```lua
GetQuestLogIsAutoComplete           = GetQuestLogIsAutoComplete,
```
[/Cataclysm/Contents/Quests/Quests.lua#L80](https://github.com/Skamer/Syling-Tracker/blob/de60823b850d9cf93e0e9c29027bd279df9a6ae0/Cataclysm/Contents/Quests/Quests.lua#L80)
add
```lua
local isAutoComplete = GetQuestLogIsAutoComplete(i)
```
[/Cataclysm/Contents/Quests/Quests.lua#L114](https://github.com/Skamer/Syling-Tracker/blob/de60823b850d9cf93e0e9c29027bd279df9a6ae0/Cataclysm/Contents/Quests/Quests.lua#L114)
replace `questData.isAutoComplete = nil -- TODO: Need check it` with
```lua
questData.isAutoComplete = isAutoComplete
```
[/Cataclysm/Contents/Quests/Quests.lua#L124](https://github.com/Skamer/Syling-Tracker/blob/de60823b850d9cf93e0e9c29027bd279df9a6ae0/Cataclysm/Contents/Quests/Quests.lua#L124)
same treatment inside the while loop add
```lua
isAutoComplete = GetQuestLogIsAutoComplete(i)
```

Similar changes for `function UpdateQuest`
[/Cataclysm/Contents/Quests/Quests.lua#L158](https://github.com/Skamer/Syling-Tracker/blob/de60823b850d9cf93e0e9c29027bd279df9a6ae0/Cataclysm/Contents/Quests/Quests.lua#L158)
add
```lua
local isAutoComplete = GetQuestLogIsAutoComplete(questLogIndex)
```
and [/Cataclysm/Contents/Quests/Quests.lua#L189](https://github.com/Skamer/Syling-Tracker/blob/de60823b850d9cf93e0e9c29027bd279df9a6ae0/Cataclysm/Contents/Quests/Quests.lua#L189)
replace the hardcoded = false with
```lua
questData.isAutoComplete = isAutoComplete
```

**Comment by Road-block** [comment]
Additionally for the 2 click handlers (header + content) in `Cataclysm/Contents/Quests/QuestView.lua`

Under [/Cataclysm/Contents/Quests/QuestView.lua#L123](https://github.com/Skamer/Syling-Tracker/blob/de60823b850d9cf93e0e9c29027bd279df9a6ae0/Cataclysm/Contents/Quests/QuestView.lua#L123)
insert
```lua
local questLogIndex = GetQuestLogIndexByID(questID)
```
Replace the two lines at [/Cataclysm/Contents/Quests/QuestView.lua#L133](https://github.com/Skamer/Syling-Tracker/blob/de60823b850d9cf93e0e9c29027bd279df9a6ae0/Cataclysm/Contents/Quests/QuestView.lua#L133) + 134
with
```lua
RemoveAutoQuestPopUp(questID)
ShowQuestComplete(questLogIndex)
```

Repeat for the other click handler
[/Cataclysm/Contents/Quests/QuestView.lua#L166](https://github.com/Skamer/Syling-Tracker/blob/de60823b850d9cf93e0e9c29027bd279df9a6ae0/Cataclysm/Contents/Quests/QuestView.lua#L166)
insert new line with
```lua
local questLogIndex = GetQuestLogIndexByID(questID)
```
Replace the two lines at [/Cataclysm/Contents/Quests/QuestView.lua#L176](https://github.com/Skamer/Syling-Tracker/blob/de60823b850d9cf93e0e9c29027bd279df9a6ae0/Cataclysm/Contents/Quests/QuestView.lua#L176) + 177
with
```lua
RemoveAutoQuestPopUp(questID)
ShowQuestComplete(questLogIndex)
```

**Comment by Road-block** [comment]
Having done the dailies for a couple days with this fix in place it works fine but it definitely needs some kind of indicator for people that play without sound on.

So you know you can click the completed quest to autodeliver and spawn the followup.

**Comment by Skamer** [comment]
Hello, 

The auto quests module was missing, so i took the one from Retail and made the necessary conversions to use the Cataclysm API. This should display the popups in the tracker.

Since i'm not a Cataclysm player and haven't been able to verify this on the PTR, i'm not 100% sure if everything is okay.

Thank you for the information provided, it's really a time-saver. In the future, if you can don't hesitate to send me a pull request.

**Comment by Road-block** [comment]
2.5.3 popup works fine 👍🏻 

This can be closed.
