### ISSUE TITLE
Quest Header Level - Remove level

### ISSUE THREAD

**Issue by Xarenia** [Skamer/Syling-Tracker#111]
As someone who only really plays max level, the ability to hide/remove the level on the quest header would be really nice, as there is no real use case for knowing that the quest is for level 80. 

![2024-09-19 01_58_43-World of Warcraft](https://github.com/user-attachments/assets/addf9f5b-2a60-47b4-b746-48eff79dc460)

Thank you for a great custom objective tracker.

**Comment by Skamer** [comment]
Hello,

In a future update, i'll add 4 policies to control the visibility of quest level:
1.  Still hide the quest level
2.  Still show the quest level
3.  Show the quest level only when the character isn't max level.
4.  Show the quest level only when the level is different than the character level.

**Comment by Xarenia** [comment]
Perfect, looking forward to it!
