### ISSUE TITLE
WOW Classic vanilla lua Error: Attempt to index field 'tag' (a number value)

### ISSUE THREAD

**Issue by fireymerlin** [Skamer/Syling-Tracker#112]
**Describe the bug**
Lua error

3x .../SylingTracker/Vanilla/Contents/Quests/QuestView.lua:234: attempt to index field 'tag' (a number value)
[string "@Scorpio/Modules/Core.lua"]:78: in function <Scorpio/Modules/Core.lua:73>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@SylingTracker/Core/Tracker.lua"]:260: in function <SylingTracker/Core/Tracker.lua:259>
[string "=(tail call)"]: ?
[string "@SylingTracker/Core/Tracker.lua"]:902: in function <SylingTracker/Core/Tracker.lua:897>
[string "=(tail call)"]: ?
[string "@SylingTracker/Core/Tracker.lua"]:882: in function <SylingTracker/Core/Tracker.lua:870>
[string "=(tail call)"]: ?
[string "@Scorpio/PLoop/System/Threading.lua"]:90: in function <Scorpio/PLoop/System/Threading.lua:87>
[string "@Scorpio/PLoop/System/Threading.lua"]:94: in function <Scorpio/PLoop/System/Threading.lua:93>
**Do you have an error log of what happened?**

**To Reproduce**
1. Disabled all addons except this one, Scopio, buggrabber, bugsack.
2. Log into a charactrer

**Expected behavior**

**What is the version of SylingTracker you use ?**
2.5.3

**What are the versions of PLoop and Scorpio you use ?**
- PLoop: 'not installed'
- Scorpio: 'r221'

**Additional context**

**Comment by Road-block** [comment]
https://github.com/Skamer/Syling-Tracker/issues/109 probably related
