### ISSUE TITLE
Classic Era: Unable to change any colours 

### ISSUE THREAD

**Issue by Xarenia** [Skamer/Syling-Tracker#114]
I only experienced this issue in Classic Era, where I'm not able to change any of the colours on the tracker, be it text or background

**Comment by Skamer** [comment]
This is related to a different API for ColorPicker on this version, triggering an error and prevent you to show the Picker. The same problem is also on Cataclysm.

**Comment by Xarenia** [comment]
Ah, I see. Makes sense then. Thanks Blizz :)

**Comment by Skamer** [comment]
At the end of Dragonflight, there was a change occured for ColorPicker API, so maybe my code before that may work on Classic.

I'll deploy a fix as soon as possible.
