### ISSUE TITLE
Add option to align quest names

### ISSUE THREAD

**Issue by alexanderstoev** [Skamer/Syling-Tracker#117]
Add an option to be able to left/right/center align the text of the quest names in the tracker.
<img width="1251" alt="slt questnames" src="https://github.com/user-attachments/assets/5729cc5f-2f74-477b-87ec-b7fe46d41a8a">

Those are already available in the headers as "Text justify V/H"

**Comment by Skamer** [comment]
Sorry for the delay. This will be available in the next release.
