### ISSUE TITLE
Quest tracking sometimes completely breaks

### ISSUE THREAD

**Issue by RyadaProductions** [Skamer/Syling-Tracker#12]
**Describe the bug**
Quests that have multiple steps or use a quest item can occasionally break the whole quest tracking untill you do a /reload

**Do you have an error log of what happened?**
```
4x ...\SylingTracker\Contents\Quests\QuestCategoryView.lua:232: table index is nil
[string "@Scorpio\Core.lua"]:321: in function <Scorpio\Core.lua:165>
[string "=(tail call)"]: ?
```

```
6x PLoop\System\Threading.lua:189: ...faceSylingTracker\Contents\Quests\Quests.lua:263: Usage: GetQuestLogSpecialItemInfo(index)
[string "@Scorpio\Core.lua"]:75: in function <Scorpio\Core.lua:70>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `AddWorldQuestWatch'
[string "@Blizzard_ObjectiveTracker\Blizzard_BonusObjectiveTracker.lua"]:168: in function `BonusObjectiveTracker_TrackWorldQuest'
[string "@Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua"]:460: in function `OnMouseClickAction'
[string "@Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua"]:157: in function `OnClick'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:146: in function <...aceBlizzard_MapCanvas\Blizzard_MapCanvas.lua:143>
```

```
245x ...faceSylingTracker\Contents\Quests\Quests.lua:263: Usage: GetQuestLogSpecialItemInfo(index)
[string "@Scorpio\Core.lua"]:75: in function <Scorpio\Core.lua:70>
[string "=(tail call)"]: ?
```

**To Reproduce**
This is not explicitly reproducable. It happens after a while of playing.

**Expected behavior**
Quest tracking shouldn't break after a while, nor need a /reload to start working again.

**Screenshots**
![image](https://user-images.githubusercontent.com/24586388/96583619-4931b980-12dd-11eb-9b12-6e00aacbd0c9.png)

**What is the version of SylingTracker you use ?**
0.3.6

**What are the versions of PLoop and Scorpio you use ?**
- PLoop: v260
- Scorpio: v055

**Comment by Skamer** [comment]
I didn't expect the quest log index could be "nil" for an unknown reason. I'd like to know the reason. Sometime the game can have weird behavior and i need to deal with.

The easy fix will be checking if the quest log index is nil before to use it. 

Have you reproduce the issue since ?

**Comment by RyadaProductions** [comment]
I have reproduced the issue multiple times.
Sadly each time it happens i don't notice it soon enough to remember what action i undertook the exact time it broke.
I will pay more attention to this when i am going for the Quest meta achievements soon.

**Comment by Skamer** [comment]
In the version 0.4, a check is done on the quest log index before to use it for fetching the item information so the error won't appear and break the update of quests.
