### ISSUE TITLE
Add translations to this AddOn

### ISSUE THREAD

**Issue by gjfLeo** [Skamer/Syling-Tracker#123]
I play World of Warcraft with zhCN. Can I contribute translations for this AddOn? I've noticed that a lot of text seems to be hard-coded; could they support localization? (Scorpio already includes a localization module.) If needed, perhaps I could also try to submit a PR directly?

**Comment by Skamer** [comment]
Hello,

I'm open to any contributions, but as you have noticed, nothing is setup yet in that regard. I'll try to get it done quickly and will inform you here when it's ready.
