### ISSUE TITLE
Scorpio

### ISSUE THREAD

**Issue by Captnmoregun** [Skamer/Syling-Tracker#125]
**Is your feature request related to a problem? Please describe.**
As long as Scorpio is a depedancy this addon will never be on my list.
**Describe the solution you'd like**
Code without Scorpio being in the loop. 

**Describe alternatives you've considered**
No alternative. Scorpio is the worst.

**Additional context**
I love the addon and yes I dll'd and used for a while, but I was disappointed when a patch hit and Syling was up to date whjile I had tons of errors for scorpio, note to other scorpio is not addon friendly.

**Comment by Skamer** [comment]
Hello,

The issue you're describing is something that can happen with any library. I'm not exactly sure what errors you encountered with Scorpio, but keep in mind that might come from my addon even if it's not indicated as such. 

Recently, there was case where Scorpio was causing errors after a recent ElvUI update. The author of Scorpio was very quick to resolve the issue, knowing that ElvUI was actually at fault. 

To answer your question, i don't plan to create a version without Scorpio, as that would literally mean recreating the addon from scratch.

I'll leave the ticket open for a little while in case you want to respond before I close it.
