### ISSUE TITLE
[Cata Classic] AutoQuests error

### ISSUE THREAD

**Issue by Road-block** [Skamer/Syling-Tracker#126]
**Describe the bug**
Lua error interacting with autocomplete quest (?)

**Do you have an error log of what happened?**
If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack]
```log
1x ...Tracker/Cataclysm/Contents/AutoQuests/AutoQuests.lua:44: attempt to index global 'M' (a nil value)
[string "@Scorpio/Modules/Core.lua"]:78: in function <Scorpio/Modules/Core.lua:73>
[string "=(tail call)"]: ?

Locals:
map = <table> {
}
(for state) = <table> {
}
(for control) = <table> {
 AUTO_QUESTS_CONTENT_SUBJECT = <table> {
 }
 __PLOOP_ENV_BSENV = <table> {
 }
}
obj = <table> {
 AUTO_QUESTS_CONTENT_SUBJECT = <table> {
 }
 __PLOOP_ENV_BSENV = <table> {
 }
}
ok = false
err = "...Tracker/Cataclysm/Contents/AutoQuests/AutoQuests.lua:44: attempt to index global 'M' (a nil value)"
```

**To Reproduce**
I am not exactly sure which of the quests had this appear, but it was one of the early Molten Front auto-complete dailies.
Possibly: [Call The Flock](https://www.wowhead.com/cata/quest=29147) > [Wings Aflame](https://www.wowhead.com/cata/quest=29148)

**Expected behavior**

**Screenshots**

**What is the version of SylingTracker you use ?**
2.6.3

**What is the version of Scorpio you use ?**
- Scorpio: 'r226'

**Additional context**

**Comment by Skamer** [comment]
Seems like a typo error. I pushed an update to fix it.

**Comment by Road-block** [comment]
Haven't had any issues since the fix 👍🏻
