### ISSUE TITLE
Archievements

### ISSUE THREAD

**Issue by Luellin** [Skamer/Syling-Tracker#15]
**Describe the bug**
The icon of the archievements its upside down in the tracker

**Do you have an error log of what happened?**
There is no error with bugsack enabled

**To Reproduce**
1. Add any archievement 
2. Check the tracker in the archievement seccion

**What is the version of SylingTracker you use ?**
Version 0.3.7

**What are the versions of PLoop and Scorpio you use ?**
- PLoop: v260
- Scorpio: Version: v055

**Comment by Skamer** [comment]
I close this ticket as the 0.4 version includes the fix provided by @TheSumm
