### ISSUE TITLE
Scenario progress bars don't update their text value.

### ISSUE THREAD

**Issue by RyadaProductions** [Skamer/Syling-Tracker#16]
**Describe the bug**
Scenario's that have a progress bar update the bar itself while the % stays on 0%.

**Do you have an error log of what happened?**
There is no error generated when this behavior is perceived

**To Reproduce**
1. Start the Void elf scenario
2. Progress untill the scenario
3. On step 4/10 where you have to repel the void the progress bar moves as you continue completing it, but the value stays on 0.

**Expected behavior**
the text value of the progress should also update to the corresponding value.

**Screenshots**
![image](https://user-images.githubusercontent.com/24586388/96991117-44147a80-1528-11eb-9c60-b2ce5fe20d22.png)

**What is the version of SylingTracker you use ?**
0.3.7

**What are the versions of PLoop and Scorpio you use ?**
- PLoop: v260
- Scorpio: v055

**Additional context**
I am not sure if this is limited to scenario's but i have seen this happen multiple times.

**Comment by RyadaProductions** [comment]
As an additional behavior that seems faulty to me:
When i go to the next step that doesn't have a progress bar based tracker, the progress bar doesn't disappear.

**Comment by Skamer** [comment]
Thank for the report.
