### ISSUE TITLE
Additions I would love

### ISSUE THREAD

**Issue by Korrigan1340** [Skamer/Syling-Tracker#18]
Love the addon! The fact that I can abandon right from the tracker is refreshing. Would love option to customize further. Mostly quality of life options:
-Change the size of the gap between categories - to take up less space vertically. Or option to remove/hide category if you wish.
-Change transparency to background - ei: categories can be hard to read in open world, depending on your location due to transparent background.
-Change colors/text size
-Option to Remove/Hide "Quests" title bar

Thank you again. I've been looking for an addon like this for some time.

**Comment by Skamer** [comment]
The addon uses a skin system. As the options are not there, you are not able yet to use it. 
My plan about it:
- [ ] Be able creating your own skin
- [ ] Share your skins : import and export feature. 
- [ ] Create a skin editor. 

The skin system is very powerful, you can modify the visual of element as you wish without need to know how the things happen behind. The skins are  simple LUA table, and shouldn't too hard to understand: 
https://github.com/Skamer/Syling-Tracker/blob/b4ca2073222382992e2ee6f968003548d4cfe564/Contents/Quests/QuestView.lua#L597-L704

A small example of what a skin can do, the positioning of the quest has been changed but i could have gone further (modify the fond, change the background, ...)

![](https://i.ibb.co/YPLWjNy/preview-skin-change.jpg)

To be honest, i cannot wait to see your creativity with this system.
