### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by AmenitradieDruidin** [Skamer/Syling-Tracker#2]
**Describe the bug**

> I always get the following error message:
> 6x SylingTracker\SylingTracker-0.1.3-release.lua:72: Usage: SLT.Database.Clean(System.ClassType) - the 1st argument can't be nil
> [string "@Scorpio\Core.lua"]:75: in function <Scorpio\Core.lua:70>
> [string "=(tail call)"]: ?

> 2x ...\SylingTracker\Contents\Quests\QuestCategoryView.lua:144: attempt to call method 'ReleaseQuestsz' (a nil value)
> [string "@Scorpio\Core.lua"]:321: in function <Scorpio\Core.lua:165>
> [string "=(tail call)"]: ?

**Do you have an error log of what happened?**
The error message just goes on. Get the message from Bugsack.

**What is the version of SylingTracker you use ?**
 8.3.0

**What are the versions of PLoop and Scorpio you use ?**
- PLoop: 8.3.0
- Scorpio: 8.3.0

**Comment by Skamer** [comment]
The errors are due to typo. I have pushed an update for fixing them. 
Sorry for disturbing.
