### ISSUE TITLE
Error message when searching option

### ISSUE THREAD

**Issue by AmenitradieDruidin** [Skamer/Syling-Tracker#21]
Hello, I always get this error message when I click on the search option in the menu:
3x [ADDON_ACTION_BLOCKED] AddOn 'SylingTracker' hat versucht die geschützte Funktion 'Search()' aufzurufen.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Search'
[string "@FrameXML\LFGList.lua"]:1756: in function `LFGListSearchPanel_DoSearch'
[string "@FrameXML\LFGList.lua"]:591: in function `LFGListCategorySelection_StartFindGroup'
[string "@FrameXML\LFGList.lua"]:382: in function `LFGListFrame_BeginFindQuestGroup'
[string "@FrameXML\LFGList.lua"]:3294: in function <FrameXML\LFGList.lua:3286>
[string "@SylingTracker\Contents\ContextMenuPatterns.lua"]:92: in function `handler'
[string "@SylingTracker\UI\ContextMenu.lua"]:288: in function `func'
[string "@PLoop\Prototype.lua"]:15639: in function <PLoop\Prototype.lua:15632>
[string "=(tail call)"]: ?

**Comment by Skamer** [comment]
I close it as the version 0.4 fixes the issue.
