### ISSUE TITLE
Dungeon quests don't show all objectives

### ISSUE THREAD

**Issue by RyadaProductions** [Skamer/Syling-Tracker#24]
**Describe the bug**
Dungeon quests sometimes don't get the correct height in the tracker.
This makes it impossible to read all the requirements for completing the Quest.

**Do you have an error log of what happened?**
No error has been created when it happened

**To Reproduce**
1. Go into a dungeon with a worldquest
2. Look at the tracker

**Expected behavior**
Correct height so all the objectives can be read

**Screenshots**
![image](https://user-images.githubusercontent.com/24586388/98102826-6301fd80-1e94-11eb-821d-4cdef44bca32.png)

**What is the version of SylingTracker you use ?**
0.4.0

**What are the versions of PLoop and Scorpio you use ?**
- PLoop: v260
- Scorpio: v055

**Comment by RyadaProductions** [comment]
As an addition sometimes it doesn't load the dungeon image either

**Comment by Skamer** [comment]
Thanks for the report, the dungeon content needs a little revision. 

For the dungeon image, it's more complex. I need searching a reliable solution to get a dungeon image from WoW API, i have thought the current one i use was enough but this seems not. I could use a hardcoded solution as fallback but before i'd like to see if it exists a better alternative.

**Comment by Skamer** [comment]
I reworked the dungeon content and make some improvements. As a result, the issue where the dungeon doesn't show all objectives should be fixed.

Remain just to find a fix for dungeon icon.
