### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by DeeGRe** [Skamer/Syling-Tracker#25]
1. Increase senstivity of a mouse scroll. Or add an option for it. I believe it would be a huge QoL if you can scroll from the top to bottom in just one scroll (I need 9 scrolls atm. Very frustrating)

2. Hide/show achievements/quests by clicking on it.
2a. Hide completed objectives. Or add an option to hide/show it. 
IF possible separately for achievements and quests. IF possible separately for EACH achievement/quest

3. Name of the locations or events (red texts) need dark background. Also would be great to have a possibility to show/hide them by clicking on it - just like achi/quest above.
![Безымянный](https://user-images.githubusercontent.com/74022446/98294697-6e067c00-1fc1-11eb-8afe-2a56825a440a.png)

P.S. thanks for an awesome addon

**Comment by Skamer** [comment]
Thank for your feedback. I appreciate it

>Increase senstivity of a mouse scroll. Or add an option for it. I believe it would be a huge QoL if you can scroll from the top to bottom in just one scroll (I need 9 scrolls atm. Very frustrating)

I have added a new slash command `/slt scrollstep 15` for setting the sensibility of scrolling in the 0.4.1 version.

>Hide/show achievements/quests by clicking on it.
2a. Hide completed objectives. Or add an option to hide/show it.
IF possible separately for achievements and quests. IF possible separately for EACH achievement/quest

I take note of that.

I have some plan for giving a way to manipulate the data sent to the view. By this way, it's possible to create a filter. For example, you will be able to intercept the quests data, modify it in removing the completed quests. The result of that is only the quests have not been completed will be displayed. Sure you can apply this same logic for completed objectives or everything else. 

> Name of the locations or events (red texts) need dark background. Also would be great to have a possibility to show/hide them by clicking on it - just like achi/quest above.

I'll look what i can do for improving that.

**Comment by DeeGRe** [comment]
Thanks! Command works just great.

![Безымянный1](https://user-images.githubusercontent.com/74022446/98426058-84d3ce00-20a8-11eb-876c-d23f37b71a03.png)
The dungeon objective shows up at the very bottom. 
Mine opinion: it should be at the top as the most recent objective just like world quests. Same for m+ (didnt test), torghast and lfr

**Comment by DeeGRe** [comment]
![2](https://user-images.githubusercontent.com/74022446/98448095-d5940700-213a-11eb-839f-2ccb207462ed.png)
Another update: This is Argus, small invasion point. Progress bar is filling at first step (i believe same at second step) but it`s always 0%

![3](https://user-images.githubusercontent.com/74022446/98448125-0ffda400-213b-11eb-983c-a681fa5ee0d3.png)
at third step bar is always looks full but still 0%

At least this scenario objective always automatically at the top (which is good).

**Comment by Skamer** [comment]
Indeed, it's not intended the achievements are above of dungeon. I need to update the value used by the different content for setting their order.

About hiding the completed objectives, i could consider adding that but only on the following form for the moment as the options are not yet built:
`/run SLT.Settings("achievement-hide-completed-objectives", true)`

For Scenario issue, It seems similar to #16 , i haven't yet had the opportunity to look what's wrong.
