### ISSUE TITLE
Syling Tracker missing

### ISSUE THREAD

**Issue by jcjolley** [Skamer/Syling-Tracker#28]
**Describe the bug**
The addon is gone.  I have used /slt show, /slt unlock, /slt lock, and /slt toggle to no avail
I recently upgraded my monitor to an ultrawide, and after doing so, the addon is gone.   I think it is probably just hiding off the side of the screen, but I can't get it to show up again.  There are no error messages, and /slt bot still hides/shows the blizzard object tracker.

**What is the version of SylingTracker you use ?**  0.4.3

**What are the versions of PLoop and Scorpio you use ?**
- PLoop: '2.6.2'
- Scorpio: '0.5.5'

**Comment by jcjolley** [comment]
Any chance we can get an /slt reset to reset all saved vars including the addon frame position?

**Comment by Skamer** [comment]
Type that and do a reload:
`/run import("SLT"); SLT.Database.SelectTable(false, "trackers", "main"); SLT.Database.SetValue("xPos", nil); SLT.Database.SetValue("yPos", nil)`

This removes the settings related to the tracker position and will reset the tracker for the next reload ui.

**Comment by jcjolley** [comment]
That fixed it!  Thank you!
