### ISSUE TITLE
Progress doesn't update correctly

### ISSUE THREAD

**Issue by monoloko88** [Skamer/Syling-Tracker#3]
**Describe the bug**
When doing world quest and maybe other quest I dont know the progress (%) is not updating at all.

**Do you have an error log of what happened?**
I dont have errors with this bug

**To Reproduce**
Just go to a world quest in zandalar or kul tiras etc and when the quest shows up and you start with it you will see it is not updating the progress in the quest tracker

**Expected behavior**

**Screenshots**
Here is a screenshot I marked with two red squares
https://postimg.cc/XpCYGMzH

**What is the version of SylingTracker you use ?**
version 0.1.4 release

**What are the versions of PLoop and Scorpio you use ?**
- PLoop: v259
- Scorpio: v051

**Additional context**
![Untitled](https://user-images.githubusercontent.com/20724793/95649230-c63e8100-0adc-11eb-9528-b011aec6623a.png)

**Comment by Skamer** [comment]
Fixed in the 0.1.5.  Thanks for reporting it.
