### ISSUE TITLE
Worldquests don't clean up properly

### ISSUE THREAD

**Issue by RyadaProductions** [Skamer/Syling-Tracker#30]
**Describe the bug**
After doing a world quest the quest is not untracked properly and remains in the quest list untill a /reload
In the attached screenshot you can see the worldquest Training regimen still visible while i am away from the world quest area as well as having it completed.

**Do you have an error log of what happened?**
No error is caused

**To Reproduce**
1. Do a worldquest
2. Sometimes it doesn't dissapear from the quest log

**Expected behavior**
After completing the World quest the quest should not appear in the tracker anymore

**Screenshots**
![image](https://user-images.githubusercontent.com/24586388/100439907-6871f280-30a4-11eb-95ed-66493660a497.png)

**What is the version of SylingTracker you use ?**
0.5.1

**What are the versions of PLoop and Scorpio you use ?**
- PLoop: v264
- Scorpio: v057

**Comment by RyadaProductions** [comment]
There is another issue with worldquests:

**Describe the bug**
When you select a worldquest on the world map you start tracking it.
So far it is fine, but after selecting a different one the previous one still appears in the Tracker.
This can be done infinitely causing more and more worldquests to be added to the tracker under the World PVP grouping.

**Do you have an error log of what happened?**
No error is caused

**To Reproduce**
Steps to reproduce the behavior:

- Select a worldquest on the world map
- The worldquest gets tracked in World PVP as well as they don't get cleaned up when you track a different world quest.

**Screenshots**
![image](https://user-images.githubusercontent.com/24586388/100441420-b8ea4f80-30a6-11eb-829e-0c42c29ae3ad.png)

**Comment by Skamer** [comment]
I see the problem. I don't have expected the tracking of world quest triggers the same event as the quests, so causing this weird behavior where the quest module react to this. 

I have finished the fix which will be included in the next update. 

A last thing, manually tracking the world quest from the world map isn't yet supported.
