### ISSUE TITLE
Torghast doesn't properly clean up/determine width

### ISSUE THREAD

**Issue by RyadaProductions** [Skamer/Syling-Tracker#33]
**Describe the bug**
Torghast powers don't clean up properly after 1 run and you go into the second run.
Also the amount of icons can expand past the width of the addon screen

**Do you have an error log of what happened?**
There are no errors

**To Reproduce**
1. Do a floor 3 torghast
2. Finish it and start another one
3. There are powers in the list that you don't have and they also have no hover tooltip

**Expected behavior**
Only shows the actually obtained powers

**Screenshots**
![Anima no tooltip and more than you own](https://user-images.githubusercontent.com/24586388/100581429-06a1ca80-32e8-11eb-9a57-5d0fba28036b.png)
![Anima outside of frame](https://user-images.githubusercontent.com/24586388/100581439-086b8e00-32e8-11eb-8944-1b255186664a.png)

**What is the version of SylingTracker you use ?**
0.5.2

**What are the versions of PLoop and Scorpio you use ?**
- PLoop: v264
- Scorpio: v058

**Comment by Skamer** [comment]
Do you know if the anima powers which shouldn't be here in the second run was anima power you have taken in your first run ?

**Comment by RyadaProductions** [comment]
Yes the powers that weren't supposed to be there were ones that i had in the previous run. Not all the ones that i had in the previous run appeared on the second run it seems to vary between 3 to 8 powers.

**Comment by nutspanther** [comment]
To add to this, I was noticing issues where the death count and floor level wouldn't update either.

**Comment by RyadaProductions** [comment]
I had the following Error today in Torghast: ```3x ...ingTracker\Contents\Torghast\TorghastContentView.lua:232: attempt to compare number with nil
[string "@Scorpio\Core.lua"]:323: in function <Scorpio\Core.lua:167>
[string "=(tail call)"]: ?```

**Comment by Skamer** [comment]
I pushed an update which will fix the issue where torghast being not correctly reset for the next run.
With the latest update (0.5.3), please let me know if you still encounter the issues.

**Comment by nutspanther** [comment]
I'm getting an issue still when I reloadui:
![image](https://user-images.githubusercontent.com/4268042/101961874-af99d080-3bd8-11eb-874a-af5f8920f7fd.png)

**Comment by nutspanther** [comment]
I was able to get in this state again last night. It happened when I chose the power that makes damage done have a "very high chance to heal for 5% of your health"

**Comment by Skamer** [comment]
Sorry for my late reply (currently i don't have too much time to give on the addon development because guild progress). I did a fix some days ago so this should be resolved.
