### ISSUE TITLE
Torghast module not updating

### ISSUE THREAD

**Issue by TotalHamman** [Skamer/Syling-Tracker#36]
**Describe the bug**
Fresh Torghast run after logging in.  Torghast module stopped updating properly before completing Floor 1.

**Expected behavior**
Torghast module updates properly throughout the entire run.

**Screenshots**
![image](https://user-images.githubusercontent.com/543169/102151375-60ea7180-3e38-11eb-8560-080d46f930b4.png)

**What is the version of SylingTracker you use ?**
0.5.3

**What are the versions of PLoop and Scorpio you use ?**
- PLoop: 'v266'
- Scorpio: 'v058'

**Comment by AmenitradieDruidin** [comment]
yes same problem

**Comment by Skamer** [comment]
Sorry for my late reply (currently i don't have too much time to give on the addon development because guild progress). I did a fix some days ago so this should be resolved.
