### ISSUE TITLE
Hey can we get the Group finder icon on the elite quests plz?

### ISSUE THREAD

**Issue by Firegodd** [Skamer/Syling-Tracker#38]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Skamer** [comment]
I don't display the group finder icon, but you can retrieve the same feature in "right clicking" the quest to open the context menu and go to "Find a group".

**Comment by Firegodd** [comment]
Ah thank you very much
