### ISSUE TITLE
Error message in Torgast

### ISSUE THREAD

**Issue by AmenitradieDruidin** [Skamer/Syling-Tracker#40]
I got this error message when selecting a skill:

3x SylingTracker\Utils\TorghastUtils.lua:51: attempt to index global 'AnimaPowerClass' (a nil value)
[string "@Scorpio\Core.lua"]:77: in function <Scorpio\Core.lua:72>
[string "=(tail call)"]: ?w

**Comment by Skamer** [comment]
Will be fixed asap, thanks for your report.
