### ISSUE TITLE
TomTom Support

### ISSUE THREAD

**Issue by jpathomas** [Skamer/Syling-Tracker#41]
**Is your feature request related to a problem? Please describe.**
My feature request is not related to a problem, it's a request that the tracker support TomTom. I have used Kaliel's tracker for sometime, and I while it has problems the thing that keeps me with it is TomTom support.

**Describe the solution you'd like**
I would like to click on a quest and have the option of setting a TomTom waypoint.

**Describe alternatives you've considered**
I am also using the built in navigation system, and it's a good addition to TomTom, but not a suitable replacement.

**Additional context**
I know I'm not the only one who depends on TomTom. I like the look and feel of Syling-Tracker ( for example the easy of resizing the moving the tracker window), but lack of TomTom support is a hard stop for me. Thank you for taking the time to consider my request.

**Comment by Xanthey** [comment]
November 2023, Wrath Classic. Would still like this feature.
