### ISSUE TITLE
Request - toggle auto-hide in combat

### ISSUE THREAD

**Issue by rcumby** [Skamer/Syling-Tracker#43]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rcumby** [comment]
Please add auto-hiding when in combat.

**Comment by Skamer** [comment]
Now implemented. 

1. In the options: My Tracker > [Tracker Name] > Visibility Rules
2. Set in the macro part: [combat] hide; show
