### ISSUE TITLE
Quest Items not removed after the quests are completed

### ISSUE THREAD

**Issue by AmenitradieDruidin** [Skamer/Syling-Tracker#47]
Hello, I wanted to ask if you are still working on the addon here? Because there were no updates for a long time.

I still have the problem, for example, that the items remain in the bar after a quest and I have to do a / reload every time. (See image)
A decay indicator on the button would also be helpful. Because items that you have to use often have cooldowns.

Will there still be updates or should you use the other Quest add-on (EskaTracker)?
I also ask for 4 other friends. Because everyone also uses the add-on. :)
![Screenshot 2021-04-23 162534](https://user-images.githubusercontent.com/39033070/115992194-a845f300-a5cc-11eb-8386-90ac5dcd923a.png)

**Comment by Skamer** [comment]
Hello,

As i log very rarely on WoW, the time i give to Syling Tracker is near of 0. It also unlikely that i'll finish the options i had initially started 6 months ago. 

Things i'm considering is to retake the options system of Eska Tracker to adapt for Syling Tracker.

**Comment by AmenitradieDruidin** [comment]
Oh that's sad to read. :(
But you're not giving up on the project, are you? :( I love this quest tracker. The tracker is so clear and chic.
I will support them again soon. Only now because of Corona I don't have that much money. :(

**Comment by Skamer** [comment]
A very very very late answer. I have some plan to rework the item bar, so i'll take this opportunity for improving and fixing the issues relative to it.

**Comment by Skamer** [comment]
I close it as the item bar has been completely reworked in the 2.0.
