### ISSUE TITLE
9.1 LUA errors

### ISSUE THREAD

**Issue by brophyba** [Skamer/Syling-Tracker#49]
PLoop\System\Threading.lua:175: SylingTracker\Core\Tracker.lua:577: attempt to index global '_Tracker' (a nil value)
[string "@Scorpio\Modules\Core.lua"]:77: in function <Scorpio\Modules\Core.lua:72>
[string "=(tail call)"]: ?

**Comment by Skamer** [comment]
fixed in the latest versio, thanks for having reported it.
