### ISSUE TITLE
This page is abandoned, the Lib is already embeded into the Scorpio

### ISSUE THREAD

**Issue by Hexus-Proud** [Skamer/Syling-Tracker#55]
**Describe the bug**
with the new update you get a big bug report and it is difficult to get the PLoop file see above

Message: ...nterface\AddOns\SylingTracker\Core\SLTFontString.lua:19: Usage: inherit(class) - The class is not provided
Time: Thu Aug 19 16:37:23 2021
Count: 1
Stack: ...nterface\AddOns\SylingTracker\Core\SLTFontString.lua:19: Usage: inherit(class) - The class is not provided
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\PLoop\Prototype.lua"]:10015: in function `inherit'
[string "@Interface\AddOns\SylingTracker\Core\SLTFontString.lua"]:19: in function `definition'
[string "@Interface\AddOns\PLoop\Prototype.lua"]:9831: in function <Interface\AddOns\PLoop\Prototype.lua:9805>
[string "@Interface\AddOns\SylingTracker\Core\SLTFontString.lua"]:18: in main chunk

Locals: (*temporary) = "Usage: inherit(class) - The class is not provided"

**What is the version of SylingTracker you use ?**  0.5.7.1.

**What are the versions of PLoop and Scorpio you use ?**  
- PLoop: project-102336 v274
- Scorpio: v097

**Comment by Skamer** [comment]
There are some change in the dependencies (PLoop is now embedded in Scorpio and is no longer a standalone), so you need to get a the latest version of Scorpio.

**Comment by KungFuPanda81** [comment]
Could you tell me were to get the laterst version of Scorpio?

**Comment by Hexus-Proud** [comment]
https://github.com/kurapica/Scorpio/releases

**Comment by KungFuPanda81** [comment]
Ok evern with that it´s now working. Ok I don´t know how to fix it.

**Comment by Hexus-Proud** [comment]
unzip the file, rename it to Scorpio, delete the old files of Scorpio in Interface/Addons/ and delete the old PLoop file, copy the new file in Addons direction.....have fun
