### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Fizgig1973** [Skamer/Syling-Tracker#59]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Ability to orient the tracker right or left.  (I have my tracker on the upper left hand of my screen. 

Ability to hide or move the scroll down bar to either side (if above is too much work)

Ability to show # of Quests, Achieves, Daily Quests etc.. in log currently. 

**Describe alternatives you've considered**
Kaliel's Tracker

**Additional context**

**Comment by Skamer** [comment]
Hello,
When you say orient the tracker right of left, this is for example only changing the scroll bar position relative to tracker ?

**Comment by Fizgig1973** [comment]
Yes, relative to the tracker.

**Comment by Skamer** [comment]
I have plans for letting you choosing where is located the scroll bar (left or right). 

Updating the scroll bar position based on the tracker position is not a hard task, it's something i already did with context menu when you right clicking on a quest. I can include this behavior in the options in addition of "left" or "right"
