### ISSUE TITLE
LUA errors when opening world map.

### ISSUE THREAD

**Issue by Vandersouls** [Skamer/Syling-Tracker#6]
EDIT Hmm. I made sure this wasn't another addon interfering by disabling all and just the addon itself and got the same lua.
however now with some enabled it's gone. (and yes the required libs are on). I'll see if I can narrow it down further.

EDIT2: Ya I can't reproduce it right now. For whatever reason it was doing it and now it's not. Someone else in the posts on the addon page experienced something similar so not sure if it is an issue.

Hi bunch of lua errors when opening the map. if you don't open it addons fine and doesn't have issues.

Message: ...ard_ObjectiveTracker\Blizzard_QuestSuperTracking.lua:42: attempt to index upvalue 'SuperTrackEventFrame' (a nil value)
Time: Wed Oct 14 16:37:58 2020
Count: 1
Stack: ...ard_ObjectiveTracker\Blizzard_QuestSuperTracking.lua:42: attempt to index upvalue 'SuperTrackEventFrame' (a nil value)
[string "@Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_QuestSuperTracking.lua"]:42: in function `QuestSuperTracking_ShouldHighlightDungeons'
[string "@Interface\AddOns\Blizzard_SharedMapDataProviders\DungeonEntranceDataProvider.lua"]:53: in function `UpdateSupertrackedHighlight'
[string "@Interface\AddOns\Blizzard_SharedMapDataProviders\DungeonEntranceDataProvider.lua"]:34: in function `RefreshAllData'
[string "@Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua"]:76: in function `OnMapChanged'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:559: in function `OnMapChanged'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:234: in function `OnMapChanged'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:59: in function `SetMapID'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:245: in function <...rface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:243>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:2893: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2738: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2606: in function <Interface\FrameXML\UIParent.lua:2602>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3457: in function `ShowUIPanel'
[string "@Interface\FrameXML\QuestLogOwnerMixin.lua"]:103: in function `SetDisplayState'
[string "@Interface\FrameXML\QuestLogOwnerMixin.lua"]:41: in function `HandleUserActionToggleSelf'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:435: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals: uiMapID = 10
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'SuperTrackEventFrame' (a nil value)"
SuperTrackEventFrame = nil

Message: ...rd_SharedMapDataProviders\WorldQuestDataProvider.lua:185: attempt to index field 'ticker' (a nil value)
Time: Wed Oct 14 16:39:34 2020
Count: 1
Stack: ...rd_SharedMapDataProviders\WorldQuestDataProvider.lua:185: attempt to index field 'ticker' (a nil value)
[string "@Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua"]:185: in function `OnHide'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:93: in function `OnHide'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:269: in function <...rface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:268>
[string "=[C]"]: in function `Hide'
[string "@Interface\FrameXML\UIParent.lua"]:2841: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2922: in function `HideUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2610: in function <Interface\FrameXML\UIParent.lua:2602>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3477: in function `HideUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:3632: in function `CloseWindows'
[string "@Interface\FrameXML\UIParent.lua"]:3675: in function <Interface\FrameXML\UIParent.lua:3665>
[string "=[C]"]: in function `securecall'
[string "@Interface\FrameXML\UIParent.lua"]:4315: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

Locals: self = <table> {
 OnClearFocusedQuestID = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:79
 EvaluateCheckBounties = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:63
 poiQuantizer = <table> {
 }
 OnMapInsetMouseLeave = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:46
 AddWorldQuest = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:308
 GetBountyQuestID = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:149
 SetMatchWorldMapFilters = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:3
 OnCanvasScaleChanged = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:50
 registeredEvents = <table> {
 }
 PingQuestID = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:153
 owningMap = WorldMapFrame {
 }
 OnSetFocusedQuestID = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:75
 activePins = <table> {
 }
 DoesWorldQuestInfoPassFilters = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:191
 ShouldShowQuest = <function> defined @Interface\AddOns\Blizzard_WorldMap\WM_WorldQuestDataProvider.lua:7
 GetMap = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:70
 OnCanvasSizeChanged = <function> defined @Interface\AddOns\Blizzard_WorldMap\WM_WorldQuestDataProvider.lua:35
 markActiveQuests = true
 checkBounties = true
 usesSpellEffect = true
 matchWorldMapFilters = false
 IsMarkingActiveQuests = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:98
 OnRemoved = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:120
 OnAdded = <function> defined @Interface\AddOns\Blizzard_WorldMap\WM_WorldQuestDataProvider.lua:15
 OnMapChanged = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:74
 OnSuperTrackingChanged = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:255
 IsUsingSpellEffect = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:23
 ClearFocusedQuestID = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:134
 SignalEv
Message: ...ard_ObjectiveTracker\Blizzard_QuestSuperTracking.lua:42: attempt to index upvalue 'SuperTrackEventFrame' (a nil value)
Time: Wed Oct 14 16:45:44 2020
Count: 2
Stack: ...ard_ObjectiveTracker\Blizzard_QuestSuperTracking.lua:42: attempt to index upvalue 'SuperTrackEventFrame' (a nil value)
[string "@Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_QuestSuperTracking.lua"]:42: in function `QuestSuperTracking_ShouldHighlightDungeons'
[string "@Interface\AddOns\Blizzard_SharedMapDataProviders\DungeonEntranceDataProvider.lua"]:53: in function `UpdateSupertrackedHighlight'
[string "@Interface\AddOns\Blizzard_SharedMapDataProviders\DungeonEntranceDataProvider.lua"]:34: in function `RefreshAllData'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:448: in function `RefreshAllDataProviders'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:476: in function `RefreshAll'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:84: in function `OnShow'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:246: in function <...rface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:243>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:2893: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2738: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2606: in function <Interface\FrameXML\UIParent.lua:2602>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3457: in function `ShowUIPanel'
[string "@Interface\FrameXML\QuestLogOwnerMixin.lua"]:103: in function `SetDisplayState'
[string "@Interface\FrameXML\QuestLogOwnerMixin.lua"]:85: in function `HandleUserActionOpenQuestLog'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:443: in function `OpenQuestLog'
[string "@Interface\FrameXML\QuestMapFrame.lua"]:700: in function `QuestMapFrame_OpenToQuestDetails'
[string "@Interface\AddOns\SylingTracker\Contents\Quests\QuestView.lua"]:83: in function `?'
[string "@Interface\AddOns\PLoop\Prototype.lua"]:15639: in function <Interface\AddOns\PLoop\Prototype.lua:15626>
[string "=(tail call)"]: ?

Locals: uiMapID = 10
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'SuperTrackEventFrame' (a nil value)"
SuperTrackEventFrame = nil
Message: ...rd_SharedMapDataProviders\WorldQuestDataProvider.lua:185: attempt to index field 'ticker' (a nil value)
Time: Wed Oct 14 16:39:41 2020
Count: 1
Stack: ...rd_SharedMapDataProviders\WorldQuestDataProvider.lua:185: attempt to index field 'ticker' (a nil value)
[string "@Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua"]:185: in function `OnHide'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:93: in function `OnHide'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:269: in function <...rface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:268>
[string "=[C]"]: in function `Hide'
[string "@Interface\FrameXML\UIParent.lua"]:2877: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2957: in function `HideUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2610: in function <Interface\FrameXML\UIParent.lua:2602>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3477: in function `HideUIPanel'
[string "@Interface\SharedXML\SharedUIPanelTemplates.lua"]:312: in function `HideParentPanel'
[string "*:OnLoad"]:1: in function `onCloseCallback'
[string "@Interface\SharedXML\SharedUIPanelTemplates.lua"]:126: in function <Interface\SharedXML\SharedUIPanelTemplates.lua:122>

Locals: self = <table> {
 OnClearFocusedQuestID = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:79
 EvaluateCheckBounties = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:63
 poiQuantizer = <table> {
 }
 OnMapInsetMouseLeave = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:46
 AddWorldQuest = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:308
 GetBountyQuestID = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:149
 SetMatchWorldMapFilters = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:3
 OnCanvasScaleChanged = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:50
 registeredEvents = <table> {
 }
 PingQuestID = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:153
 owningMap = WorldMapFrame {
 }
 OnSetFocusedQuestID = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:75
 activePins = <table> {
 }
 DoesWorldQuestInfoPassFilters = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:191
 ShouldShowQuest = <function> defined @Interface\AddOns\Blizzard_WorldMap\WM_WorldQuestDataProvider.lua:7
 GetMap = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:70
 OnCanvasSizeChanged = <function> defined @Interface\AddOns\Blizzard_WorldMap\WM_WorldQuestDataProvider.lua:35
 markActiveQuests = true
 checkBounties = true
 usesSpellEffect = true
 matchWorldMapFilters = false
 IsMarkingActiveQuests = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:98
 OnRemoved = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:120
 OnAdded = <function> defined @Interface\AddOns\Blizzard_WorldMap\WM_WorldQuestDataProvider.lua:15
 OnMapChanged = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:74
 OnSuperTrackingChanged = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:255
 IsUsingSpellEffect = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:23
 ClearFocusedQuestID = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:134
 SignalEvent = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:9
Message: ...ard_ObjectiveTracker\Blizzard_QuestSuperTracking.lua:42: attempt to index upvalue 'SuperTrackEventFrame' (a nil value)
Time: Wed Oct 14 16:43:30 2020
Count: 2
Stack: ...ard_ObjectiveTracker\Blizzard_QuestSuperTracking.lua:42: attempt to index upvalue 'SuperTrackEventFrame' (a nil value)
[string "@Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_QuestSuperTracking.lua"]:42: in function `QuestSuperTracking_ShouldHighlightDungeons'
[string "@Interface\AddOns\Blizzard_SharedMapDataProviders\DungeonEntranceDataProvider.lua"]:53: in function `UpdateSupertrackedHighlight'
[string "@Interface\AddOns\Blizzard_SharedMapDataProviders\DungeonEntranceDataProvider.lua"]:34: in function `RefreshAllData'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:448: in function `RefreshAllDataProviders'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:476: in function `RefreshAll'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:84: in function `OnShow'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:246: in function <...rface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:243>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:2893: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2738: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2606: in function <Interface\FrameXML\UIParent.lua:2602>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3457: in function `ShowUIPanel'
[string "@Interface\FrameXML\QuestLogOwnerMixin.lua"]:103: in function `SetDisplayState'
[string "@Interface\FrameXML\QuestLogOwnerMixin.lua"]:41: in function `HandleUserActionToggleSelf'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:435: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals: uiMapID = 10
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'SuperTrackEventFrame' (a nil value)"
SuperTrackEventFrame = nil
Message: ...rd_SharedMapDataProviders\WorldQuestDataProvider.lua:185: attempt to index field 'ticker' (a nil value)
Time: Wed Oct 14 16:43:31 2020
Count: 2
Stack: ...rd_SharedMapDataProviders\WorldQuestDataProvider.lua:185: attempt to index field 'ticker' (a nil value)
[string "@Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua"]:185: in function `OnHide'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:93: in function `OnHide'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:269: in function <...rface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:268>
[string "=[C]"]: in function `Hide'
[string "@Interface\FrameXML\UIParent.lua"]:2841: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2922: in function `HideUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2610: in function <Interface\FrameXML\UIParent.lua:2602>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3477: in function `HideUIPanel'
[string "@Interface\FrameXML\QuestLogOwnerMixin.lua"]:101: in function `SetDisplayState'
[string "@Interface\FrameXML\QuestLogOwnerMixin.lua"]:41: in function `HandleUserActionToggleSelf'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:435: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals: self = <table> {
 OnClearFocusedQuestID = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:79
 EvaluateCheckBounties = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:63
 poiQuantizer = <table> {
 }
 OnMapInsetMouseLeave = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:46
 AddWorldQuest = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:308
 GetBountyQuestID = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:149
 SetMatchWorldMapFilters = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:3
 OnCanvasScaleChanged = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:50
 registeredEvents = <table> {
 }
 PingQuestID = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:153
 owningMap = WorldMapFrame {
 }
 OnSetFocusedQuestID = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:75
 activePins = <table> {
 }
 DoesWorldQuestInfoPassFilters = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:191
 ShouldShowQuest = <function> defined @Interface\AddOns\Blizzard_WorldMap\WM_WorldQuestDataProvider.lua:7
 GetMap = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:70
 OnCanvasSizeChanged = <function> defined @Interface\AddOns\Blizzard_WorldMap\WM_WorldQuestDataProvider.lua:35
 markActiveQuests = true
 checkBounties = true
 usesSpellEffect = true
 matchWorldMapFilters = false
 IsMarkingActiveQuests = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:98
 OnRemoved = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:120
 OnAdded = <function> defined @Interface\AddOns\Blizzard_WorldMap\WM_WorldQuestDataProvider.lua:15
 OnMapChanged = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:74
 OnSuperTrackingChanged = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:255
 IsUsingSpellEffect = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:23
 ClearFocusedQuestID = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:134
 SignalEvent = <f

**Comment by BloodDragon2580** [comment]
I have the same problem.

**Comment by Skamer** [comment]
I have more information about this.
There are 3 cases:
1. After a reload UI, if you have disabled the Blizzard objective tracker then you open the map, **you will trigger the error**
2. After a reload UI, if you have disabled the Blizzard objective then you enable it before opening the map, **you won't trigger the error.**
3. After the loading or reload, if you have enabled the Blizzard objective tracker then you open the map,  **you won't trigger the error**. 

This is very likely you are in the case 1. 

The problem is related to the way on how i disable the Blizzard objective tracker for replacing it, this seems like SuperTrackEventFrame isn't created during this process, causing error later once you open the map.

I'm searching a fix about it.
