### ISSUE TITLE
Hide when in Combat

### ISSUE THREAD

**Issue by redgunner2** [Skamer/Syling-Tracker#61]
**Is your feature request related to a problem? Please describe.**

I like to have a tidy UI and when I am in Combat I don't like to see the quests, before I installed your addon I used default with an addon that would hide in combat, but this addon is much more eye candy so was hoping you could add this option.

**Describe the solution you'd like**

When I am solo I would like quests to show but hide when im Combat

**Describe alternatives you've considered**

I used an addon before for default quests that would to hide but prefer this.

**Additional context**
![image](https://user-images.githubusercontent.com/117452385/199971934-26892130-0c73-40be-b650-c699b086cd53.png)

Thank you for your addon and it will definitely be very popular!

**Comment by Skamer** [comment]
Thank you, this is definitely in my todo list.

**Comment by Skamer** [comment]
Now implemented. 

1. In the options: My Tracker > [Tracker Name] > Visibility Rules
2. Set in the macro part: [combat] hide; show

**Comment by Spegeli** [comment]
> Now implemented.
> 
> 1. In the options: My Tracker > [Tracker Name] > Visibility Rules
> 2. Set in the macro part: [combat] hide; show

There is an issue with the Macro Condition function, because when we use this, all other visibility Rules are ignored. For Example:

M+: Hide and Macro not used: Quest Tracker not showen in M+
M+: Hide and with Macro Condition "[combat] hide;show", Quest Tracker is only Hidden in Combat, but not out of Combat in M+

For Example i want to Hide the Tracker in M+ Completly, but in Raid and other Instances only when in Combat.

My current Config: http://i.epvpimg.com/1x04dab.png

**Comment by Skamer** [comment]
> > Now implemented.
> > 
> > 1. In the options: My Tracker > [Tracker Name] > Visibility Rules
> > 2. Set in the macro part: [combat] hide; show
> 
> There is an issue with the Macro Condition function, because when we use this, all other visibility Rules are ignored. For Example:
> 
> M+: Hide and Macro not used: Quest Tracker not showen in M+ M+: Hide and with Macro Condition "[combat] hide;show", Quest Tracker is only Hidden in Combat, but not out of Combat in M+
> 
> For Example i want to Hide the Tracker in M+ Completly, but in Raid and other Instances only when in Combat.
> 
> My current Config: http://i.epvpimg.com/1x04dab.png

In you case, you should change your macro to `[combat] hide; ignore`

The 'hide' or 'show' value will say explicitly the tracker must be hidden or shown, this is why the other rules are ignored. You should remove 'show' or use 'ignore'.

`[combat] hide; ignore` and `[combat] hide` are equivalent.
