### ISSUE TITLE
slash commands not working

### ISSUE THREAD

**Issue by sidain** [Skamer/Syling-Tracker#62]
The slash commands, mainly "/slt toggle", no longer works, and just seems to bring up the main addon interface.

**Comment by Skamer** [comment]
Hello
From the version 1.0.0, i have removed the slash commands as their features have been translated to the option panel you can open with /slt or clicking on the addon minimap icon.

**Comment by sidain** [comment]
Bummer, ok, ty.

**Comment by Skamer** [comment]
This seems i haven't thought for people using that in macro, so i'll bring back them in a next update.

**Comment by sidain** [comment]
It would be most appreciated.
Tyvm

**Comment by Skamer** [comment]
For the slash commands, i plan adding the following ones:
- `/slt show trackers` show all trackers
-  `/slt show itembar` show the item bar 
- `/slt show all` show all trackers and the item bar
-  `/slt show`  shortcut for /slt show all 
-  `/slt show tracker main` show the tracker with for id main.

These behaviors will also be expanded for:
- `/slt hide`
- `/slt lock`
- `/slt unlock`

**Comment by sidain** [comment]
For what its worth, In the past, toggle was the main one for me, so I could have a single macro button for showing and hiding the tracker when I wanted screen space clear

**Comment by Skamer** [comment]
Ok, so i'll add also `/slt toggle`

**Comment by Skamer** [comment]
Here a complete list of slash commands have been implemented, and will be available in the next update.

<details> 
  <summary> /slt show</summary>

`/slt show` show all the trackers and the item bar
`/slt show all` the same as above 
`/slt show itembar` show only the item bar 
`/slt show trackers` show only all the trackers 
`/slt show tracker main` show only the main tracker 
`/slt show tracker second` show only the tracker with for id: second 
</details>
<details> 
  <summary> /slt hide</summary>

`/slt hide` hide all the trackers and the item bar 
`/slt hide all` the same as above 
`/slt hide itembar` hide only the item bar 
`/slt hide trackers` hide only all the trackers 
`/slt hide tracker main` hide only the main tracker 
 `/slt hide tracker second` hide only the tracker with for id: second 
</details>
<details> 
  <summary> /slt toggle</summary>

`/slt toggle itembar` toggle the visibility of item bar 
`/slt toggle tracker main` toggle the visibility of main tracker 
`/slt toggle tracker third` toggle the visibility of tracker with for id: third
</details>

<details> 
  <summary> /slt lock</summary>

`/slt lock` lock all the trackers and the item bar 
`/slt lock all` the same as above 
`/slt lock itembar` lock only the item bar 
`/slt lock trackers` lock only all the trackers 
`/slt lock tracker main` lock only the main tracker 
`/slt lock tracker second` lock only the tracker with for id: second 
</details>

<details> 
  <summary> /slt unlock</summary>

`/slt unlock` unlock all the trackers and the item bar 
`/slt unlock all` the same as above 
`/slt unlock itembar` unlock only the item bar 
`/slt unlock trackers` unlock only all the trackers 
`/slt unlock tracker main` unlock only the main tracker 
`/slt unlock tracker second` unlock only the tracker with for id: second 
</details>

<details> 
  <summary> /slt tlock</summary>

`/slt tlock itembar` toggle the lock setting of item bar 
`/slt tlock tracker main` toggle the lock setting of main tracker 
`/slt tlock tracker third` toggle the lock setting of tracker with for id: third
</details>

**Comment by sidain** [comment]
Those will be useful, thank you.
