### ISSUE TITLE
Unable to hand in quests that do not have an NPC to hand into

### ISSUE THREAD

**Issue by dapal-003** [Skamer/Syling-Tracker#64]
**Describe the bug**
Some quests require you to hand them in via the objective tracker. Using syling tracker, you cannot hand these in.

**Do you have an error log of what happened?**
No errors appear, simply the option to hand in the quest is not shown.

**To Reproduce**
1. Accept a quest that leads to a hand in without a NPC. The one I encountered it on was: https://www.wowhead.com/quest=38964
2. Finish quest
3. Click on quest in tracker
4. Click on Complete quest
5. Nothing happens.

**Expected behavior**
When clicking on complete quest, the quest will be handed in.

**Screenshots**
![](https://cdn.astolfo.nl/z/mcjJYO.png)
**What is the version of SylingTracker you use ?**
1.1.0
**What are the versions of PLoop and Scorpio you use ?**
- PLoop: Version included in Scorpio v169
- Scorpio: v169

**Additional context**
Using the original tracker results in a different window being shown that can be used to hand in the quest.

**Comment by dapal-003** [comment]
Just now noticed that there is an extra menu item all the way on the top of the tracker where you can hand in quests. That one works, so I guess this is a minor bug that the wow version doesn't work

**Comment by Skamer** [comment]
I identified the issue where the quest module doesn't flag correctly these quests except after a reload. I'll provide a fix as soon as possible once i encounter one.
