### ISSUE TITLE
Add "Profession" to Contents Tracked

### ISSUE THREAD

**Issue by bioandroid** [Skamer/Syling-Tracker#66]
**Is your feature request related to a problem? Please describe.**
When I select "Track Recipe" when browsing items from the Crafting Orders NPC the tracked recipe does not show in the Syling Tracker. When the addon is disabled the tracked recipe appears in the default Blizzard quest tracker, below the quests, in a section labeled "Profession." 

**Describe the solution you'd like**
Allow the addon to track "Profession" tasks similar to the default blizz UI. Add an option to turn it on/of via the "Contents Tracked" tab.

**Describe alternatives you've considered**
Only option right now is to disable the addon to see the tracked recipe

**Comment by Skamer** [comment]
The profession has been implemented in the next update (2.0.x).
