### ISSUE TITLE
Mythic Plus Pull percentage

### ISSUE THREAD

**Issue by AngelosNaoumis** [Skamer/Syling-Tracker#67]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When you pull a pack to display how much % it is going to give (as other mythic plus timer addons)

**Describe alternatives you've considered**
MythicPlusTimer addon

**Additional context**

**Comment by Skamer** [comment]
I close it as the pull percent has been implemented in the next version (2.0.x)  if you have the addon Mythic Dungeon Tools. 
In addition of that, this get also a new visual.

![image](https://github.com/Skamer/Syling-Tracker/assets/849450/7dbdd25e-9a88-4c1e-8f8d-d37366979924)
