### ISSUE TITLE
More Customization Options

### ISSUE THREAD

**Issue by Fendoran** [Skamer/Syling-Tracker#69]
I'd like to see more **Customization** regarding coloration of texts, texts sizes and backgrounds of the individual types.

I'd also like to see a minimize feature, similarly if not identical to the standard quest tracker system, where as if you click the **﹀** "button" it minimizes the quest tracker, and a **︿** to open it?

I'd like to see a auto zone feature, where quests appear on the side based on the zone you're in, if you have quests there, show, if not, don't show (Like a toggle setting, depending on if you want it or not)

I would also love to see the use icons linked to each quest, appear beside their respective quest, like what you've done already, except you should be able to interact with it.

Best Regards
**Fendoran**

**Comment by Skamer** [comment]
Hello,

> I would also love to see the use icons linked to each quest, appear beside their respective quest, like what you've done already, except you should be able to interact with it

Unfortunately, i am unable to do it without causing major issues to tracker. For doing that, i need using protected frames which have restrictions such as not enable to modify their position, visibility and attributes in combat. In addition of that, they propagate these restrictions to all frames are anchored to them. 
For resume, this would make the tracker and all its content considered as 'protected frames', and would prevent me changing their position and visibility in combat. This would cause problems, the more notable one is the scrolling system would no longer work in combat.

This is why the 'on use' buttons contained in the items bar which is a protected frame is separated and not anchored to tracker.

For your other requests, the customization part is currently my top priority, the code for adding its support is being designed. The minimize and autozone features are also on my todo list.

**Comment by Fendoran** [comment]
The button part, I can live without, but the fact that you're working on all my other requests, is a huge deal for me, I used to use SorhaQuestLog, it's nice, used it for a while, but I downloaded yours yesterday, and I can't get enough of it, honestly, It's a genious idea, simple love it, keep up the awesome work man, appreciate it!
