### ISSUE TITLE
Quest reward tooltips

### ISSUE THREAD

**Issue by Erieeroot** [Skamer/Syling-Tracker#71]
WoW Retail 10.1
Syling v1.2.2
Scorpio v186

I have found that with ONLY Syling tracker and scorpio enabled.  If you click on a quest in the tracker, then hover over the quest rewards in the quest window that comes up, tooltips do not appear.   Also on occasion when opening the map or questlog manually they do not appear, or if they do, hovering over them for ~10sec will sometimes cause the tooltips to vanish....then you have to reopen the window to get them back.  It seems very hit or miss.

There are no LUA errors that I have seen.  I could record a video and link it if that would help any.  Love the addon, so if I can help at all please let me know!

**Comment by Skamer** [comment]
I'm not sure where the issue comes, probably a bad use of GameTooltip from my side,

As i'm actively developping the next major update and i plan to rework the quests part, i delay the resolution of this issue for this update.
