### ISSUE TITLE
Pop Up Quests are not always displayed.

### ISSUE THREAD

**Issue by AmenitradieDruidin** [Skamer/Syling-Tracker#72]
**Describe the bug**
Since I'm currently leveling a lot of characters with my friend - from LVL 0 to 70 - we both often have the problem that some pop-up quests are not displayed. Various quests are affected. Instance quest as well as normal quests.
Unfortunately, neither of us get an error message so that I can report it. What often helps is a /reload. But sometimes it's a bit annoying..

The last quest I remember was the Chormies - Cataclysm: Onward to Adventure in Kalimdor pop up quest: https://www.wowhead.com/quest=60887/cataclysm-onward-to-adventure-in-kalimdor.Or if you choose the Dranor time, the beginning quest where you have to loot the letter. (Horde). If I find any more quests, I'll be happy to report them here later. We want to continue leveling up over the weekend.

**Do you have an error log of what happened?**
Unfortunately no error message received from Bugsack.

**Screenshots**
https://i.imgur.com/FDWOnzr.png 

**What is the version of SylingTracker you use ?**
Version 1.2.2

**What are the versions of PLoop and Scorpio you use ?**
- PLoop: ? - not found
- Scorpio: v186

**Additional context**
Error comes as written above, not only with me. But also with my friend. We've often reminded each other that if we don't see the popup window we need to reload. :D
Feedback/idea: Perhaps the windows could also be displayed in a more conspicuous manner? Maybe a glowing frame around it. Or that this pop-up window then flashes. It's also easy to overlook when it does show up.

**Comment by Skamer** [comment]
Hello,

Thanks for all this detailed information, it has been very helpful. 

The data for the quest popups was correct, but the element responsible for displaying them had a height issue. I have push a fix to address this.
