### ISSUE TITLE
Quests are not showing as "closed".

### ISSUE THREAD

**Issue by AmenitradieDruidin** [Skamer/Syling-Tracker#73]
**Describe the bug**
We had 2 quests where the syling tracker didn't show the quests as "closed":
Defend the Drill - https://www.wowhead.com/quest=25799/defend-the-drill 
Engineering a Disaster - https://www.wowhead.com/quest=12688/engineering-a-disaster
Runeforging: Preparation For Battle - https://www.wowhead.com/quest=12842/runeforging-preparation-for-battle
How To Win Friends And Influence Enemies - https://www.wowhead.com/quest=12720/ 

**Do you have an error log of what happened?**
Unfortunately no message from Bugsack

**Expected behavior**

**Screenshots**
![WoWScrnShot_060423_190516 Kopie](https://github.com/Skamer/Syling-Tracker/assets/39033070/1f374fd0-23c5-493c-b46c-fccce471aacd)
![352124456_789548159289992_5473285607858839773_n](https://github.com/Skamer/Syling-Tracker/assets/39033070/e7c8a5c7-3bcb-4969-8ed9-78e811b001c3)
![351509912_1415025352664067_3081214121637588609_n](https://github.com/Skamer/Syling-Tracker/assets/39033070/4eb221a7-bc60-4432-b0e4-ec183d97e5ab)

**What is the version of SylingTracker you use ?**
1.2.3

PS: And thanks for the quick fix for the pop up quest. It got better. Nevertheless, you always have to be careful, you quickly overlook these "pop-up" quests. But until now we wouldn't have to do a /reload anymore. Thank you <3

**Comment by Skamer** [comment]
Hello,

Thanks for all these detailed information. 

I agree the popup quests can sometimes be missed. This is especially true when you have already scrolled down, as they are displayed at the top of scrolling content. A solution you can try is to create a new tracker designed for displaying them, maybe this will suit you.  This is in my plans to give a way to customize the popup (background, border, font settings).

Now, coming back to this issue. 

I have updated the quest part (the last update was there are 3 years ago). This should now clearly indicate you when the quest just needs to be turned in. 

I have also made some other improvements and fixes:
- The quest now use waypoints when needed. This will help you to navigate to the quest area  (for example: 'Take the portal to Stormwind'). 
- For the quests requiring a money amount, this will show the amount to pay if you don't have enough.
- In case where the quest is failed, this will clearly be indicated.

**Comment by AmenitradieDruidin** [comment]
Thanks for the information. And thanks for the great work and updates. :)
