### ISSUE TITLE
World Quest tracker did not clear itself properly after completion.

### ISSUE THREAD

**Issue by rknauber** [Skamer/Syling-Tracker#79]
**Describe the bug**
Completed a dragonriding race WQ and the tracker seemed to be stuck "complete" even though I had completed it and left the area.

**Do you have an error log of what happened?**
`7x ...s/SylingTracker/Contents/WorldQuests/WorldQuests.lua:63: attempt to compare number with nil
[string "@Scorpio/Modules/Core.lua"]:78: in function <Scorpio/Modules/Core.lua:73>
[string "=(tail call)"]: ?

Locals:
map = <table> {
  = <function> defined @SylingTracker/SylingModule.lua:105
  = <function> defined @SylingTracker/SylingModule.lua:105
  = <function> defined @SylingTracker/SylingModule.lua:105
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
  = <function> defined @SylingTracker/SylingModule.lua:105
  = <function> defined @SylingTracker/SylingModule.lua:105
  = <function> defined @SylingTracker/SylingModule.lua:105
}
(for control) = <table> {
 QuestUtils_IsQuestWorldQuest = <function> defined @FrameXML/QuestUtils.lua:377
 OnActive = <function> defined @SylingTracker/Contents/WorldQuests/WorldQuests.lua:34
 _ActiveOnEvents = <table> {
 }
 WORLD_QUESTS_CACHE = <table> {
 }
 DebugTools = <userdata>
 QUEST_LOG_UPDATE = <function> defined @SylingTracker/Contents/WorldQuests/WorldQuests.lua:124
 RegisterObservableContent = <function> defined Argument_Validate_00aa:3
 BecomeActiveOn = <function> defined @SylingTracker/Contents/WorldQuests/WorldQuests.lua:30
 pairs = <function> defined =[C]:-1
 QUEST_ACCEPTED = <function> defined @SylingTracker/Contents/WorldQuests/WorldQuests.lua:111
 GetTaskInfo = <function> defined =[C]:-1
 _ActiveOnHandler = <function> defined @SylingTracker/Contents/WorldQuests/WorldQuests.lua:30
 ipairs = <function> defined =[C]:-1
 _Syling__Active = true
 Utils = <userdata>
 IsWorldQuest = <function> defined @FrameXML/QuestUtils.lua:377
 HasWorldQuests = <function> defined @SylingTracker/Utils/Quests.lua:46
 __PLOOP_ENV_BSENV = <table> {
 }
 GetQuestObjectiveInfo = <function> defined =[C]:-1
 UpdateWorldQuest = <function> defined @SylingTracker/Contents/WorldQuests/WorldQuests.lua:53
 QuestsContentSubject = <userdata>
 PERCENTAGE_STRING = "%d%%"
 GetQuestProgressBarPercent = <function> defined =[C]:-1
 _ActivatingEventArgs = <table> {
 }
 __ActiveOnEvents__ = <userdata>
 GetTasksTable = <function> defined =[C]:-1
 C_QuestLog = <table> {
 }
 RequestLoadQuestByID = <function> defined =[C]:-1
 QUEST_DATA_LOAD_RESULT = <function> defined @SylingTracker/Contents/WorldQuests/WorldQuests.lua:92
 QUEST_REMOVED = <function> defined @SylingTracker/Contents/WorldQuests/WorldQuests.lua:99
 _ActiveByEvent = "QUEST_ACCEPTED"
 WORLD_QUESTS_CONTENT_SUBJECT = <table> {
 }
 API = <userdata>
 __PLOOP_ENV_OWNNS = <userdata>
 __SystemEvent__ = <userdata>
 LoadWorldQuests = <function> defined @SylingTracker/Contents/WorldQuests/WorldQuests.lua:38
}
obj = <table> {
 QuestUtils_IsQuestWorldQuest = <function> defined @FrameXML/QuestUtils.lua:377
 OnActive = <function> defined @SylingTracker/Contents/WorldQuests/WorldQuests.lua:34
 _ActiveOnEvents = <table> {
 }
 WORLD_QUESTS_CACHE = <table> {
 }
 DebugTools = <userdata>
 QUEST_LOG_UPDATE = <function> defined @SylingTracker/Contents/WorldQuests/WorldQuests.lua:124
 RegisterObservableContent = <function> defined Argument_Validate_00aa:3
 BecomeActiveOn = <function> defined @SylingTracker/Contents/WorldQuests/WorldQuests.lua:30
 pairs = <function> defined =[C]:-1
 QUEST_ACCEPTED = <function> defined @SylingTracker/Contents/WorldQuests/WorldQuests.lua:111
 GetTaskInfo = <function> defined =[C]:-1
 _ActiveOnHandler = <function> defined @SylingTracker/Contents/WorldQuests/WorldQuests.lua:30
 ipairs = <function> defined =[C]:-1
 _Syling__Active = true
 Utils = <userdata>
 IsWorldQuest = <function> defined @FrameXML/QuestUtils.lua:377
 HasWorldQuests = <function> defined @SylingTracker/Utils/Quests.lua:46
 __PLOOP_ENV_BSENV = <table> {
 }
 GetQuestObjectiveInfo = <function> defined =[C]:-1
 UpdateWorldQuest = <function> defined @SylingTracker/Contents/WorldQuests/WorldQuests.lua:53
 QuestsContentSubject = <userdata>
 PERCENTAGE_STRING = "%d%%`

**To Reproduce**
As above completed dragonriding wq and it did not clear properly from the tracker after completion. I believe it was in the Waking Shore on a cliff of several waterfalls. Honestly forget exact location as I didn't notice this until I was in the next zone.

**Screenshots**
![image](https://github.com/Skamer/Syling-Tracker/assets/406300/60825b57-c36c-44b0-b7aa-edcdc0fd900d)

**What is the version of SylingTracker you use ?**
Package the commits on the development branches #52: Commit [1468d83](https://github.com/Skamer/Syling-Tracker/commit/1468d83ad845880ff21d42718568baadaf3b47fd) pushed by [Skamer](https://github.com/Skamer)

**What are the versions of PLoop and Scorpio you use ?**
- PLoop: Not installed
- Scorpio: v196

**Additional context**
I hope that is the right error log as it was the last thing that showed in my bugsack. Should note I'm using World Quest Tracker as well with it's own tracker popped out on it's own. Unless I pop it out on it's own it won't show with Syling Tracker enabled.

**Comment by Skamer** [comment]
This should be fixed in the recent commit.
