### ISSUE TITLE
Lua-Error: "script ran too long"

### ISSUE THREAD

**Issue by Digawen** [Skamer/Syling-Tracker#81]
At irregular intervals I got a Lua error, which also caused my game to freeze for 1-2 seconds. (no FPS drop)

At the end of the M+ my game hung up completely.

I also tried it in a 2nd M+, same result, but it seemed that the problem would only occur as soon as the first boss was defeated. 

At first I also thought it was due to a Weakaura.
(https://wago.io/M+Timer)

But even after deleting and restarting WoW before the 2nd M+, there were still errors.

**Version of SylingTracker: 2.0.0
Version of Scorpio: v197** 

**Lua-Error:**

180x Scorpio/Modules/Core.lua:78: script ran too long
[string "@Scorpio/Modules/Core.lua"]:78: in function <Scorpio/Modules/Core.lua:73>
[string "=(tail call)"]: ?

Locals:
map = <table> {
  = <function> defined @SylingTracker/SylingModule.lua:105
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
  = <function> defined @SylingTracker/SylingModule.lua:105
}
(for control) = <table> {
 OnActive = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:35
 _ActiveOnEvents = <table> {
 }
 DebugTools = <userdata>
 GetMapUIInfo = <function> defined =[C]:-1
 GetInstanceTextureFileID = <function> defined Argument_Validate_006:3
 GetActiveKeystoneInfo = <function> defined =[C]:-1
 GetAffixInfo = <function> defined =[C]:-1
 RegisterObservableContent = <function> defined Argument_Validate_00aa:3
 UPDATE_INSTANCE_INFO = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:113
 GetTime = <function> defined =[C]:-1
 UpdateDungeonTexture = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:67
 BecomeActiveOn = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:31
 GetInstanceInfo = <function> defined =[C]:-1
 API = <userdata>
 _ActiveOnHandler = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:31
 ipairs = <function> defined =[C]:-1
 WORLD_STATE_TIMER_STOP = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:156
 LE_WORLD_ELAPSED_TIMER_TYPE_CHALLENGE_MODE = 2
 _Syling__Active = true
 C_ChallengeMode = <table> {
 }
 Utils = <userdata>
 CHALLENGE_MODE_START = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:139
 GetCriteriaInfo = <function> defined =[C]:-1
 KEYSTONE_CONTENT_SUBJECT = <table> {
 }
 __PLOOP_ENV_BSENV = <table> {
 }
 C_Scenario = <table> {
 }
 GetInfo = <function> defined =[C]:-1
 GetWorldElapsedTime = <function> defined =[C]:-1
 CHALLENGE_MODE_DEATH_COUNT_UPDATED = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:162
 select = <function> defined =[C]:-1
 _ActivatingEventArgs = <table> {
 }
 _ActiveByEvent = "CHALLENGE_MODE_START"
 __ActiveOnEvents__ = <userdata>
 GetActiveChallengeMapID = <function> defined =[C]:-1
 __SystemEvent__ = <userdata>
 WORLD_STATE_TIMER_START = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:146
 SylingTracker_ENEMY_PULL_COUNT_CHANGED = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:169
 KeystoneContentSubject = <userdata>
 KEYSTONE_UPDATE = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:133
 GetStepInfo = <function> defined =[C]:-1
 __PLOOP_ENV_OWNNS = <userdata>
 UpdateObjectives = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:41
 UpdateKeystoneInfo = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:78
}
obj = <table> {
 OnActive = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:35
 _ActiveOnEvents = <table> {
 }
 DebugTools = <userdata>
 GetMapUIInfo = <function> defined =[C]:-1
 GetInstanceTextureFileID = <function> defined Argument_Validate_006:3
 GetActiveKeystoneInfo = <function> defined =[C]:-1
 GetAffixInfo = <function> defined =[C]:-1
 RegisterObservableContent = <function> defined Argument_Validate_00aa:3
 UPDATE_INSTANCE_INFO = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:113
 GetTime = <function> defined =[C]:-1
 UpdateDungeonTexture = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:67
 BecomeActiveOn = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:31
 GetInstanceInfo = <function> defined =[C]:-1
 API = <userdata>
 _ActiveOnHandler = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:31
 ipairs = <function> defined =[C]:-1
 WORLD_STATE_TIMER_STOP = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:156
 LE_WORLD_ELAPSED_TIMER_TYPE_CHALLENGE_MODE = 2
 _Syling__Active = true
 C_ChallengeMod

**Comment by Skamer** [comment]
In the 2.0.2, the distance of quests is no longer updated in the instance, this was previously the case when your character is moving, this refresh every second.

**Comment by Skamer** [comment]
I identified the problem, and its origin, the 2.0.3 should fix the issue. In addition of that, the timers will now be updated every 0.5s (instead of each frame) for reducing the performance cost. 

Remain other things i need to check, and plan to do an additional improvement/fix in the next update.

**Comment by Digawen** [comment]
Thank you for your work, with version 2.0.3 there were no problems during the M+ run, but at the end of the instance I had a long freeze that lasted several minutes. 

The freeze started exactly when I defeated the final boss. 

Including the following Lua error.



26x Scorpio/Modules/Core.lua:78: script ran too long
[string "@Scorpio/Modules/Core.lua"]:78: in function <Scorpio/Modules/Core.lua:73>
[string "=(tail call)"]: ?

Locals:
map = <table> {
  = <function> defined @SylingTracker/SylingModule.lua:105
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
  = <function> defined @SylingTracker/SylingModule.lua:105
}
(for control) = <table> {
 OnActive = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:36
 _ActiveOnEvents = <table> {
 }
 DebugTools = <userdata>
 GetMapUIInfo = <function> defined =[C]:-1
 GetInstanceTextureFileID = <function> defined Argument_Validate_006:3
 GetActiveKeystoneInfo = <function> defined =[C]:-1
 GetAffixInfo = <function> defined =[C]:-1
 RegisterObservableContent = <function> defined Argument_Validate_00aa:3
 UpdateObjectives = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:43
 GetTime = <function> defined =[C]:-1
 UpdateDungeonTexture = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:69
 BecomeActiveOn = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:32
 GetInstanceInfo = <function> defined =[C]:-1
 API = <userdata>
 _ActiveOnHandler = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:32
 ipairs = <function> defined =[C]:-1
 WORLD_STATE_TIMER_STOP = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:167
 LE_WORLD_ELAPSED_TIMER_TYPE_CHALLENGE_MODE = 2
 _Syling__Active = true
 GetWorldElapsedTime = <function> defined =[C]:-1
 C_ChallengeMode = <table> {
 }
 UpdateDeathCounter = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:106
 __ActiveOnEvents__ = <userdata>
 strsub = <function> defined =[C]:-1
 CHALLENGE_MODE_START = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:150
 GetCriteriaInfo = <function> defined =[C]:-1
 tonumber = <function> defined =[C]:-1
 select = <function> defined =[C]:-1
 GetDeathCount = <function> defined =[C]:-1
 __PLOOP_ENV_BSENV = <table> {
 }
 _ActivatingEventArgs = <table> {
 }
 C_Scenario = <table> {
 }
 GetInfo = <function> defined =[C]:-1
 _ActiveByEvent = "CHALLENGE_MODE_START"
 CHALLENGE_MODE_DEATH_COUNT_UPDATED = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:173
 KeystoneContentSubject = <userdata>
 GetActiveChallengeMapID = <function> defined =[C]:-1
 SylingTracker_ENEMY_PULL_COUNT_CHANGED = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:182
 __SystemEvent__ = <userdata>
 WORLD_STATE_TIMER_START = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:157
 Utils = <userdata>
 KEYSTONE_UPDATE = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:144
 UPDATE_INSTANCE_INFO = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:120
 GetStepInfo = <function> defined =[C]:-1
 __PLOOP_ENV_OWNNS = <userdata>
 KEYSTONE_CONTENT_SUBJECT = <table> {
 }
 UpdateKeystoneInfo = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:80
}
obj = <table> {
 OnActive = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:36
 _ActiveOnEvents = <table> {
 }
 DebugTools = <userdata>
 GetMapUIInfo = <function> defined =[C]:-1
 GetInstanceTextureFileID = <function> defined Argument_Validate_006:3
 GetActiveKeystoneInfo = <function> defined =[C]:-1
 GetAffixInfo = <function> defined =[C]:-1
 RegisterObservableContent = <function> defined Argument_Validate_00aa:3
 UpdateObjectives = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:43
 GetTime = <function> defined =[C]:-1
 UpdateDungeonTexture = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:69
 BecomeActiveOn = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:32
 GetInstanceInfo = <function> defined =[C]:-1
 API = <userdata>
 _ActiveOnHandler = <function> defined @SylingTracker/Contents/Keystone/Keystone.lua:32
 ipairs = <fu

**Comment by Skamer** [comment]
With the latest version (2.0.4), i improved my previous fix so no performance issues should be occur now.

**Comment by Digawen** [comment]
I can confirm this. Everything is running great again. Thanks for your work.
