### ISSUE TITLE
Quests category not responding!!!

### ISSUE THREAD

**Issue by FinalLightning** [Skamer/Syling-Tracker#82]
Since I installed Syling Tracker 2.0 Update, my Quest category no longer works. I even uninstalled the addon and deleted folders but that didn't work. The other tabs work perfectly except that. Please solve this problem quickly.

**Comment by Skamer** [comment]
Can you take a screenshot ? this would helpful for me to see exactly the problem.

**Comment by FinalLightning** [comment]
Yes ok i make it maybe Video too?


Skamer ***@***.***> schrieb am So. 10. Dez. 2023 um 14:14:

**Comment by FinalLightning** [comment]
Final Lightning ***@***.***> schrieb am So. 10. Dez. 2023 um 16:49:

**Comment by Skamer** [comment]
> Yes ok i make it maybe Video too?

If you can also do a video ,it would be helpful.

**Comment by Skamer** [comment]
Without other information included, i close it the ticket as i don't know what is exactly the problem and i'm unable to reproduce the issue.
