### ISSUE TITLE
Blizzard Objective Tracker not staying hidden

### ISSUE THREAD

**Issue by imershon** [Skamer/Syling-Tracker#83]
'Show Blizzard Objective Tracker' setting not 'keeping' the tracker hidden

No errors are being generated in the logs

1. 'Show Blizzard Objective Tracker' initially unticked however Blizzard tracker shown
2. Ticking/Unticking will hide Blizzard's tracker however it will reappear at next logon

**Comment by Skamer** [comment]
Have you checked with only Syling Tracker enabled ?

**Comment by imershon** [comment]
Turns out it was Dugi Questing Essential addon intefering with Syling Tracker's hide option. Makes no difference what options are selected in DQE just with it loaded at all prevents it being hidden. Works fine without it.

**Comment by Arkewas** [comment]
ATM clicking between Syling Tracker POI's doesn't automatically switch between DUGI arrows' objectives (maybe Skamer will add full integration between the 2 addons in the future :) ) but you can click on POI's over the map to do it.

**Comment by imershon** [comment]
> Hi, if you are interested I manage to hide completely the default Wow objective tracker by using the addon MoveIt https://www.curseforge.com/wow/addons/moveit It's a fantastic addon that let you scale, resize, reposition and hide almost any WoW frame. The last update is November 28, 2022 but it works fine. Use the command /mit to open its setting then add ObjectiveTrackerFrame to the frames list then check "Hide frame". Dugi Questing Essential and Syling tracker, currently the best objective tracker around, work like a charm together.

Thanks Arkewas - Moveit works like a charm :) - have also mentioned issue to DQE as well to see if they'll have a squiz

**Comment by Arkewas** [comment]
> > Hi, if you are interested I manage to hide completely the default Wow objective tracker by using the addon MoveIt https://www.curseforge.com/wow/addons/moveit It's a fantastic addon that let you scale, resize, reposition and hide almost any WoW frame. The last update is November 28, 2022 but it works fine. Use the command /mit to open its setting then add ObjectiveTrackerFrame to the frames list then check "Hide frame". Dugi Questing Essential and Syling tracker, currently the best objective tracker around, work like a charm together.
> 
> Thanks Arkewas - Moveit works like a charm :) - have also mentioned issue to DQE as well to see if they'll have a squiz

You're welcome.
