### ISSUE TITLE
Add Height/Width Settings to Tracker

### ISSUE THREAD

**Issue by Hayato2846** [Skamer/Syling-Tracker#84]
**Is your feature request related to a problem? Please describe.**
Currently, there's only the option to change the scale of your trackers which means everything gets way bigger when you just want to set a longer tracker for example. My UI setup is built with 4k resolution in mind and the current default tracker is  good as it is just a little bit too short. 

**Describe the solution you'd like**
Add Width/Height Settings beside Scale.

**Describe alternatives you've considered**
Increase scale and manually try to 'shrink' every aspect of the tracker (e.g. fonts, icon size, etc.) but it's kinda hard and not very user-friendly.

**Additional context**
Please let me finally replace Kaliel's Tracker with Syling Tracker ♥

**Comment by Skamer** [comment]
There are no Width/Height settings in the options, but there is an other way for resizing the tracker as you want:
- When you unlock the tracker, a "resize" indicator will be displayed to the bottom right
![image](https://github.com/Skamer/Syling-Tracker/assets/849450/d7efd4aa-9320-4b3e-bfb0-ea5f9cefc9f3)

I agree you can easily miss it as this isn't very visible, i'll improve that in the future.

**Comment by Hayato2846** [comment]
Thank you very much :) Works as intended. Cheers!
