### ISSUE TITLE
Compatibility with Dugi Questing Essential and TomTom addons

### ISSUE THREAD

**Issue by Arkewas** [Skamer/Syling-Tracker#87]
Hello Skamer,

I would like to see implemented the aforementioned feature. I mean that when clicking on a Syling Tracker POI, maybe with a opional key like CTRL, ALT or SHIFT, the Dugi arrow or TomTom arrow switches to that POI. Both are popular addons, specially TomTom but I don't know if the feature can be implemented right away or you need to contact that addons' developers.

Regards

**Comment by Skamer** [comment]
Hello,

I started the TomTom support but not yet finished. For Dugi, i need to check first but this shouldn't hard to implement.

**Comment by Arkewas** [comment]
Hi Skamer,

Thank you very much. I think that this feature will make Syling Tracker even better.

**Comment by Arkewas** [comment]
Also thank you for supporting Dugi. Personally I prefer Dugi to TomTom because when you set a manual waypoint on World Map, Dugi arrows points to the nearest Flight Master needed to reach that waypoint. Also when opening the Flight Map, it marks in red color the destination's flight master. TomTom arrow simply points to the waypoint, at least I haven't found a TomTom option to show the shortest route like Dugi.

**Comment by Arkewas** [comment]
Furthermore when you click on a World Map quest's objective POI the Dugi arrow switches to it, TomTom arrow doesn't. Essentially Dugi has a better interaction with the World Map unless I'm missing some TomTom options.

**Comment by Arkewas** [comment]
Hello Skamer,

the Dugi feature I'm referring to, as descripted on Dugi Questing Essential Curseforge page:

**Taxi feature will automatically create the fastest possible route using flight master, teleport spells, portals, boats zeppelins and available items.**

On that page I just asked them if they can make Dugi addon compatible with Syling Tracker.
