### ISSUE TITLE
The War Within (11.0)

### ISSUE THREAD

**Issue by Skamer** [Skamer/Syling-Tracker#91]
Hello,

Sorry for the lack of updates as i am not as active on WoW as before. I plan to update the addon for the War Within, but i don't want to commit to new features just yet. My prioriity is to fix any issues caused by the 11.0 version. 

I will wait until the prepatch is available on the European servers to push an update. In the meantime, if you play on a NA realms  [ you can download a version 11.0 of the addon here.](https://github.com/Skamer/Syling-Tracker/actions/runs/10061282223/artifacts/1730953500)

**Comment by Arkewas** [comment]
Hello,
 I've updated Syling Tracker to version  2.1.0 and forced outdated Scorpio lib to load but Syling Tracker isn't working (it doesm't show in game). Maybe I'm wrong but it seems that with the new WoW patch the outdated addons won't work even if they are forced to load.

**Comment by Skamer** [comment]
The update was done a bit urgently. I started working on it yesterday on the PTR realms, but the servers were down while i was preparing the update. So, i didn't have the time to check everything, just made sure the addon loads at least. That's why you might encouter a LUA error that breaks the addon which i didn't get. Do you have anything on your end ?

Currently you need to force to load the outdated addons, even if Scorpio is not updated yet, the addon should be displayed. 

Another thing, i incremented too much the toc version so the addon is considered outdated when it's shouldn't be, i will fix that.

**Comment by Arkewas** [comment]
I don't get Lua errors and I have loaded outdated Scorpio but Syling tracker isn't showing anyway. I have tested others outdated addons and they  won't work even if they are forced to load. Also outdated addons opions aren't visible in Wow settings panel even if they are forced to load.

**Comment by Arkewas** [comment]
Hello Skamer,
I must apologize because I was wrong. I had enabled the outdated addons but the checkbox "Load outdated addons" wasn't checked and I didn't realize it, maybe the WoW patch disabled it, I don't know. After flagging that checkbox the outdated addons were loaded correctly and Syling Tracker is working well. Also thank you for updating it, I like it and it's the only tracker who lets you create separate trackers (achievements, objectives, scenarios, tasks etc.

**Comment by Arkewas** [comment]
BTW  I'm getting a Scorpio lua error but  Syling Tracker is working fine

9x Scorpio/PLoop/System/Threading.lua:184: bad argument #1 to '?' (not a numerical value - Usage: local spellBookItemInfo = C_SpellBook.GetSpellBookItemInfo(spellBookItem))
[string "@Scorpio/Modules/Core.lua"]:78: in function <Scorpio/Modules/Core.lua:73>
[string "=(tail call)"]: ?

Locals:
map = <table> {
}
(for state) = <table> {
}
(for control) = <table> {
 __PLOOP_EVENT_Scorpio_OnEnable = <table> {
 }
 _MacroMap = <table> {
 }
 handler = <table> {
 }
 __PLOOP_ENV_BSENV = <table> {
 }
 _MacroMapTemplate = "_MacroMap[%d]  = %q
"
 _Profession = <table> {
 }
 _StanceMap = <table> {
 }
 _StanceMapTemplate = "_StanceMap[%d] = %d
"
}
obj = <table> {
 __PLOOP_EVENT_Scorpio_OnEnable = <table> {
 }
 _MacroMap = <table> {
 }
 handler = <table> {
 }
 __PLOOP_ENV_BSENV = <table> {
 }
 _MacroMapTemplate = "_MacroMap[%d]  = %q
"
 _Profession = <table> {
 }
 _StanceMap = <table> {
 }
 _StanceMapTemplate = "_StanceMap[%d] = %d
"
}
ok = false
err = "Scorpio/PLoop/System/Threading.lua:184: bad argument #1 to '?' (not a numerical value - Usage: local spellBookItemInfo = C_SpellBook.GetSpellBookItemInfo(spellBookItem))"

**Comment by Fizgig1973** [comment]
Same error as above. Also the default objective tracker is not being hidden any longer. 

No other addons installed.

**Comment by Arkewas** [comment]
> Also the default objective tracker is not being hidden any longer.

Hello, to hide the default objective tracker I use this addon  https://www.curseforge.com/wow/addons/edit-mode-expanded

**Comment by Skamer** [comment]
The Delves (new feature of The War Within) are now fully supported by the addon:
![image](https://github.com/user-attachments/assets/f2347fa2-f6d3-41ff-98f8-d7174f9f8404)
