### ISSUE TITLE
Anchor-point setting

### ISSUE THREAD

**Issue by rousseauxy** [Skamer/Syling-Tracker#92]
I love the add-on but I'm missing an "anchor" option. I switch frequently between my laptop screen and an ultra wide on my desk, so when I switch I need to reposition the tracker.

If there was an option to anchor it to, for example, top right and the X and Y value are based on that anchor-point I wouldn't have to do that (kaliel's tracker has this for example as do elvui frames)

Can't imagine I'm the only one with this "issue" so throwing it in as an enhancement :)

Thanks for considering this!

**Comment by Skamer** [comment]
Hello,

Thank you for pointing out this issue. I will add an option to change the anchor where the tracker is relatively positioned.

**Comment by rousseauxy** [comment]
Wouldn't call it really an issue, but with this enhancement i can ditch kaliel's tracker in favor of yours :D
Thanks for the wonderfull addon!

Another issue i've noticed is that the default objective tracker stays active even when the option isn't selected to show it, toggle-ing it solves it though, but will make another issue if it hasn't been listed yet :)

**Comment by Skamer** [comment]
A first iteration is now available in the today update. 

![image](https://github.com/user-attachments/assets/8d91d300-2835-4832-a694-578f25e63737)

**Comment by rousseauxy** [comment]
Just updated and works like a charm!
