### ISSUE TITLE
Game crashes. Or it freezes

### ISSUE THREAD

**Issue by nDER-CHRIS** [Skamer/Syling-Tracker#93]
Hello, community
I have the problem. When I am in a large group, for example a raid or WeldBoss, the game seems to hang. Or freezes or crashes

**Comment by nDER-CHRIS** [comment]
This can only be due to the add-on Syling-Tracker
I've already tried it. Without the add-on everything works perfectly. When I then switch on the add-on then the problems arise

**Comment by Skamer** [comment]
Hello,

Without more information and me being unable to get the problem, it would be hard to find where coming from.  Can you give the following ones:

- the addon and the Scorpio version you use  ?
- Do you have errors lua ?
- Do you encounter the problem while you are in raid instances ?
- Do you encounter the problem only when you are in combat ?
- The list of addons you use with Syling Tracker.
- Can you give me your computer spec (cpu, gpu and ram)  ?

**Comment by nDER-CHRIS** [comment]
I only have .addon running.
Syling-Tracker 2.1.4 110.2
Scorpio  v206 11.0.0

no Lua errors?

AMD 5 5600
Ram 32 GB
Nvidia geforce 4070

And that I've only had this problem since 11.0.0. Before that I didn't have this problem.

Wasn't a raid or something like that I always have to. Turn off the addon

**Comment by roxaos** [comment]
Also encountering this problem. Unsure if it's an issue with Scorpio or Syling Tracker, but considering Syling Tracker is dependent on Scorpio figured I'd also comment here.

Only two addons enabled.
No Lua errors
Frame rate drop occurs at all times but gets extremely bad, unplayable levels, during raids or high traffic world events.

As Chris mentioned, didn't have this problem prior to 11.0.0.

**Comment by Skamer** [comment]
Thanks for the information both of you.

I suspect something but i'm unable to check now, could you try to remove the code below and say me if there are improvements.

https://github.com/Skamer/Syling-Tracker/blob/f24c88360690c4289bc6218123b89c9b1d76f904/Contents/Quests/Quests.lua#L506-L530

**Comment by roxaos** [comment]
If there was an improvement it was very slight, the frame drops are still happening with Syling Tracker enabled and that code removed.

**Comment by raptormama** [comment]
I've had this issue and it seems to happen if Scorpio is enabled and Syling Tracker is not, so from my personal experience it may be an issue with Scorpio.

**Comment by roxaos** [comment]
Disabling Syling tracker and keeping Scorpio enabled resolved the frame drops for me, may be how Scorpio is interacting with certain addons(?).

**Comment by Skamer** [comment]
Could you try to rollback to Scorpio v202 for an test, and say me if there are also frame drops ?

**Comment by roxaos** [comment]
Rollingback Scorpio to v202 resolved the issue.

**Comment by raptormama** [comment]
Seems to help for me as well - lingering lag is likely from the event bosses. I'll keep an eye on it.

Scorpio 202 will need a manual fix (which I can do) to update how it gets spellbook item information. Hopefully the cause of this issue can be pinned down soon so it's safe to go back to auto updating it.

Thanks, everyone! This had been driving me crazy.

**Comment by kurapica** [comment]
> Rollingback Scorpio to v202 resolved the issue. Stutters here and there but nothing I can quite attribute to the Syling Tracker/Scorpio v202 combo.

The main change in Scorpio v202 to v206 is auto import apis that blz moved from the global to C_xxx, so the addons can share the same codes between several game versions, I add one namespace for each C_xxx for global access.

When addon access variables not defined in the addon, it'll check those namespaces and cache that if existed(won't hit the performance).

But if the variable not existed in those namesspace and _G, it'll keep check the next time(hit the performance if there are many C_xxx namespaces)

I pushed a new Scorpio v207, and combine all thsoe C_xxxx namespace to one, should fix the problem, If you try, please give me a feedback.

For skamar, consider the auto-cache behavior, you can edit the Platform.lua,  modify

```lua
ENV_ALLOW_GLOBAL_VAR_BE_NIL = false
```

So any global access failed will be throw out.

**Comment by Skamer** [comment]
I noticed some issues with the function that updates the distance of quests, could be executed multiple times simultaneously under certain conditions instead of just once. I fixed this in 2.1.5 .

Thanks @kurapica  for the update and the precisions. I've started to fix the missing global access.

**Comment by kurapica** [comment]
> Thanks @kurapica for the update and the precisions. I've started to fix the missing global access.

I checked the missing global access and fix several bugs in the v208. So you can start with that version.
