### ISSUE TITLE
Expand From Bottom

### ISSUE THREAD

**Issue by travisg100** [Skamer/Syling-Tracker#95]
Would it be possible to add the option to grow and expand from bottom to top?

I have a very bottom based UI and would love it if it could expand from the bottom growing up!

**Comment by Skamer** [comment]
Hello,

I'll take a look at this after i finish to implement the Delves (new content from Wrath the Within), but at first glance, i'm not optimistic. 

Maybe i'm having trouble visualizing it, do you have an example of what you want it to look like ?

**Comment by Skamer** [comment]
Unfortunately, i confirm that I could not implement it.

**Comment by travisg100** [comment]
> Unfortunately, i confirm that I could not implement it.

Thats too bad, guess I’ll just have to wait for Keliel’s Tracker to get updated. Thanks for looking into it!

**Comment by travisg100** [comment]
> Interesting, Kaliel’s Tracker implements this feature ?

Yeah, when I get off work I’ll try to get you some screenshots

**Comment by Skamer** [comment]
> > Interesting, Kaliel’s Tracker implements this feature ?
> 
> Yeah, when I get off work I’ll try to get you some screenshots

It's likely that I misunderstood your request, the screenshots will help me better understand what you wanted.

**Comment by Skamer** [comment]
Have you take some screenshots ?

**Comment by kasiopec** [comment]
I don't know how would you screenshot it, but if you collapse tracker and then expand it will animate from bottom to top.

**Comment by travisg100** [comment]
> I don't know how would you screenshot it, but if you collapse tracker and then expand it will animate from bottom to top.

Sorry I haven’t screenshotted it yet, but yeah that’s exactly right. Basically I have my mini map in the bottom corner and it expands up from that when you click on the various headers.

**Comment by Skamer** [comment]
With the recent version, you can put the minimize button where you want relative of tracker.
![image](https://github.com/user-attachments/assets/e223bcca-c082-43cc-92d4-2253e637c818)

I think it's what you're searching.
