### ISSUE TITLE
TomTom compatibility

### ISSUE THREAD

**Issue by Arkewas** [Skamer/Syling-Tracker#97]
Hello Skamer,
I don't know if it depends on you or on TomTom addon's developer but would it be possible to add the compatibility between the 2 addons?

**Comment by Skamer** [comment]
Hello,

I'll include an experimental integration of TomTom in the next release. This could be enabled from the options.
![image](https://github.com/user-attachments/assets/90844ea0-7a25-43ac-9dbe-8a3c60a30818)

The version be deployed as soon as i checked it.

**Comment by Arkewas** [comment]
Hi,
thank you very much for adding this feature.
