### ISSUE TITLE
TomTom integration

### ISSUE THREAD

**Issue by Arkewas** [Skamer/Syling-Tracker#98]
Hello Skamer,
I logged just to say that TomTom integration works very well and I didn't get lua errors so far. I noticed that TomTom option "Enable automatic quest objective waypoints" seems not to be working but the same behavior occurs with Blizzard's objective tracker so I think that it's TomTom's fault and not Syling Tracker one. Btw I prefer to set manual waypoints and furthermore Syling Tracker sorts objectives by distance (Blizzard's tracker doesn't), so it's easy to manually select the nearest one which is on top of Syling Tracker's objectives.
Thanks for maintaing and updating Syling Tracker.

**Comment by Skamer** [comment]
For now, i've kept it simple : the addon use WoW's supertracking system.  I'm open to any suggestions if you think something is missing. 

Another thing , it currently only supports quests. Eventually, i plan to add world quests and collectables, as well as improve text formatting.

**Comment by Arkewas** [comment]
I think Syling Tracker it's working fine. Unfortunately TomTom addon doesn't work as it should, even with Blizzard's tracker, because: 
1) TomTom arrow doesn't shows up when I accept new quests
2) TomTom arrow doesn't automatically switch to the new objective when a quest is updated.

Some days ago I posted these issues on Curseforge TomTom page https://www.curseforge.com/wow/addons/tomtom/comments
